### ISSUE TITLE
[REQ] Specify profile to use via cmd-line

### ISSUE THREAD

**Issue by Rossbro2** [cagnulein/qdomyos-zwift#1189]
**Is your feature request related to a problem? Please describe.**
Not a problem per-se, mostly a user-experience improvement.  You can change profiles after QZ is started, but it takes extra clicks and a reboot of the app to accomplish this.  It would be much quicker & easier to be able to specify which profile you'd like loaded via cmd-line instead of requiring users to start QZ, click the menu, select a profile to use, then restart the app.

**Describe the solution you'd like**
Ability to start the app with a specified profile instead of limiting the user to whatever profile was last used.

i.e.:
`qdomyos-zwift.exe -profile Kyle`
or
`qdomyos-zwift.exe -profile SomeoneElse`

**Describe alternatives you've considered**
- Not requiring a reboot after selecting a different profile (as Roberto mentioned, this would require a lot of rework and a rewrite)

**Additional context**
See [this comment](https://www.facebook.com/groups/149984563348738/posts/536715541342303/?comment_id=536824697998054&reply_comment_id=571129897900867&notif_id=1674193764526084&notif_t=group_comment_mention) on facebook

@cagnulein 👀

**Comment by cagnulein** [comment]
done @Rossbro2 when the build is completed, you will see the new version here https://github.com/cagnulein/qdomyos-zwift/actions/runs/3968799815 on the bottom

**Comment by Rossbro2** [comment]
> done @Rossbro2 when the build is completed, you will see the new version here https://github.com/cagnulein/qdomyos-zwift/actions/runs/3968799815 on the bottom

Whoa, that was fast!  Thanks, @cagnulein! I'll give it a test and close after confirming!

**Comment by Rossbro2** [comment]
@cagnulein  hmm I've tried several different things and it's still not starting with a different profile specified in the cmd-line.  Am I doing something wrong?  Has this been tested?

**Comment by cagnulein** [comment]
@Rossbro2 sorry i forgot to mention that you need to add the extension so

-profile name.qzs

**Comment by cagnulein** [comment]
i added the extension directly in the code here https://github.com/cagnulein/qdomyos-zwift/actions/runs/3973598085

let me know and in case send me a debug log

now run with -profile name

**Comment by cagnulein** [comment]
@Rossbro2 any news?

**Comment by Rossbro2** [comment]
Unfortunately, it still doesn't work :( here are some screenshots:

![image](https://user-images.githubusercontent.com/37418852/214146203-067cf749-e0de-450f-95db-c8c7169a2a44.png)
![image](https://user-images.githubusercontent.com/37418852/214146400-3a1a5f72-75be-4c1d-9070-e794eff01efa.png)

**Comment by cagnulein** [comment]
did you get the last build? in case i will check myself tomorrow.

maybe there is something obvious that i'm missing

**Comment by cagnulein** [comment]
@Rossbro2 mmm are you sure about the arguments in this way? maybe you need to put "" to surround them?

try on the command line directly

**Comment by Rossbro2** [comment]
Here's a debug log:
[debug-Mon_Jan_23_14_48_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10483537/debug-Mon_Jan_23_14_48_31_2023.log)

**Comment by cagnulein** [comment]
thanks @Rossbro2 check my previous comments

**Comment by Rossbro2** [comment]
> thanks @Rossbro2 check my previous comments

Yup I did.  I tried with the following with the build you most recently mentioned but nothing seems to work:
`qdomyos-zwift.exe -profile Betsy`
`qdomyos-zwift.exe "-profile Betsy"`
`qdomyos-zwift.exe -profile "Betsy"`

It always just pulls up my profile (Kyle)

**Comment by cagnulein** [comment]
ok i'm checking this today
thanks for the test

**Comment by cagnulein** [comment]
fixed and tested @Rossbro2 sorry for the inconvenience
https://github.com/cagnulein/qdomyos-zwift/actions/runs/3994030054

**Comment by Rossbro2** [comment]
Tested & works great!  Thanks @cagnulein!
