### ISSUE TITLE
[BUG] Start/Pause buttons display on top of screen

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#147]
Beta 2.3.1
When "Top Bar" is turned off, the Start/Pause buttons are still showing on the main display.
![141716972_426833581765748_8111279798004295220_n](https://user-images.githubusercontent.com/6604478/105966123-19f7ba80-6039-11eb-9761-fbad1837c879.jpg)

**Comment by cagnulein** [comment]
yes, thanks. i've already fixed it ;) this is why i need all of them on github, so you will be notified ;)

**Comment by ptrinephi** [comment]
It appears the fix is no longer there.  Beta 2.3.6 still shows the pause/start/stop buttons on top when then the top bar is set to disabled.

**Comment by cagnulein** [comment]
@ptrinephi are you sure?

**Comment by ptrinephi** [comment]
This beta 2.3.6

![2021-01-31_21-56-29](https://user-images.githubusercontent.com/6604478/106420408-74b15d80-640f-11eb-9bdc-dd8726bd0e4a.png)
![2021-01-31_21-56-19](https://user-images.githubusercontent.com/6604478/106420412-767b2100-640f-11eb-95e4-1756defefc26.png)

**Comment by cagnulein** [comment]
Argh, ok i Will check again! Thanks

Il lun 1 feb 2021, 07:00 3phi <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
i checked the code and it's ok. Maybe you've changed the top bar settings without restarting the app?

**Comment by ptrinephi** [comment]
Hmm! I restart the app all the time.

⁣

**Comment by cagnulein** [comment]
ok i will check again

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 1 feb 2021 alle ore 08:22 3phi <notifications@github.com> ha
scritto:

**Comment by cagnulein** [comment]
ok i guess i understood and fixed now. It will be avaiable in the 2.3.7

**Comment by ptrinephi** [comment]
We're almost there, you missed the "pause" button.

![2021-02-01_14-52-43](https://user-images.githubusercontent.com/6604478/106528325-6873e180-649d-11eb-95a8-5f25cb314455.png)

**Comment by cagnulein** [comment]
Argh so strange, ok i Will check it

Il lun 1 feb 2021, 23:55 3phi <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
@ptrinephi yes you were right ;) fixed it again!

**Comment by ptrinephi** [comment]
3rd time is a charm, I have faith in you my friend ;-)

**Comment by cagnulein** [comment]
it's all fault that the people who want the start pause instead of stop
pause :D

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 2 feb 2021 alle ore 08:15 3phi <notifications@github.com> ha
scritto:

**Comment by ptrinephi** [comment]
I know!
