### ISSUE TITLE
[BUG] Proform Rower (Proform Sport RL) cannot change resistance from app

### ISSUE THREAD

**Issue by brupec** [cagnulein/qdomyos-zwift#1643]
Hello,

On proform sport RL rower, all infos are sent correctly from rower to QZ, but when changing resistance on QZ, it doesn't change on rower (also not moving in QZ, + and - are like inactive)

Included log was like:

1) rower started, QZ started, connected to qz in resistance 3, all infos are brought correctly
2) tried various time + and - buttons, without effect
3) manually change rower resistance to 1 on the machine, it shows correctly to 1 in QZ
4) tried various time + button without effect
5) stopped qz

Smartphone is Android 13 google pixel 7
Tested on latest paid version on google play 2.14.0

[debug-Tue_Sep_12_10_11_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12584048/debug-Tue_Sep_12_10_11_06_2023.log)

Thanks in advance

**Comment by cagnulein** [comment]
Hi @brupec I guess I got the issue, your rower as a different resistance message.
Could you please follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device using the proform app to change the resistance directly?
Let me know

**Comment by brupec** [comment]
Here you go. I couldn't find a way to change the resistance in the app so I started a training, it went from 1 to 6 then to 7 I think.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/12585161/btsnoop_hci.log)

**Comment by brupec** [comment]
oh like I go 1 to 24 then 24 to 1 something like that ?

**Comment by cagnulein** [comment]
yes exactly with maybe 10 seconds between each changes

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 set 2023 alle ore 15:04 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
Here you go
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/12588622/btsnoop_hci.log)
Also this one was btsnoop_hci.log.last originally, had to rename to leave it here
[btsnoop_hci2.log](https://github.com/cagnulein/qdomyos-zwift/files/12588629/btsnoop_hci2.log)

went 1 to 24 and then back to 1, first around 6 second pause between each to go up, then 3s to go down

**Comment by cagnulein** [comment]
thanks i will check this in the next days

Il giorno mar 12 set 2023 alle 18:15 brupec ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @brupec I just finished the code! Please click here to join the private beta group. You have to see the version 2.16.12 
I will upload it later today.
When you installed it, please enable the new proform rower setting that I created for you in the rower setting and restart qz

Let me know!

**Comment by brupec** [comment]
Thanks a lot! I'll try after you upload new version on store, for now I have 2.16.7

**Comment by cagnulein** [comment]
hah I forgot the link to join into the closed group https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

**Comment by brupec** [comment]
Still see 2.16.7 after clicking the link (but I already was in the beta I
joined it in google play yesterday)

Le mer. 13 sept. 2023, 15:29, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
ok so you should leave the beta and join it back again. It should take some hours to complete this process

**Comment by brupec** [comment]
humm weird, I quited the beta, uninstalled, wait for 2.14.0 to show again,
then followed the link, joined the testing program, wait for it to appear
in beta in google play, and still 2.16.7

I'll see tomorrow if it changed, maybe your new upload has not been taken
into account by google play yet

Le mer. 13 sept. 2023 à 16:21, Roberto Viola ***@***.***> a
écrit :

**Comment by brupec** [comment]
Hi my friend, no change 😔

Le mer. 13 sept. 2023, 17:25, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
let's wait, I also pushed it on the open beta channel, but Google is still
reviewing it

Il giorno gio 14 set 2023 alle 06:37 brupec ***@***.***> ha
scritto:

**Comment by brupec** [comment]
Hi, finally google published update! But it is still not changing resistance, I activated proform sport rl in rower options, restarted and tried disable auto resistance, same
Any idea? For the closed beta group is it linked to mail adress?

**Comment by cagnulein** [comment]
could you please attach a fresh debug log so i can check it if my
modifications are right? did you try to change resistance from qz starting
from resistance 1?

Il giorno gio 21 set 2023 alle 12:08 brupec ***@***.***> ha
scritto:

**Comment by brupec** [comment]
Hi,
Here is the new bluetooth log

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/12701788/btsnoop_hci.log)

Yes I started from 1. Also tried from other speeds.

I also noticed than when I reach 24 (max speed of the rower) it shows 1 on QZ. Up to 23 the correct speed is showed in QZ.
Maybe the bug is from there. You'll see when on rower I was on speeds arount 22/23 then it's 24. When I got back to the real 1 speed I was around 1/2/3 speeds. Each time I was pressing multiple times + and - in qz to try to change it but no reaction

Thanks

**Comment by cagnulein** [comment]
Hi nope I need a debug log not a hci snoof one :)
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
sorry for the confusion

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 set 2023 alle ore 16:27 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
Allright too here you go ;-) but you have a hci too in case ahah.

[debug-Fri_Sep_22_16_35_35_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12701951/debug-Fri_Sep_22_16_35_35_2023.log)

Good that I did it again because I checked all speeds this time and actually 5,8,13,16,24 all show 1 in QZ. Other shows good value. I didn't test all of them in previous test.

I think before all speed where showing good, in previous beta without activating proform sport RL.

and in a few occasion I tried too to play with + and -
I also played with top right icon (auto resistance) should changing resistance with +/- works in both options enabled and disabled ?

thanks

**Comment by cagnulein** [comment]
ok thanks, i will check this in the next days.
crazy days at work (on my main job i mean)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 set 2023 alle ore 16:47 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
OK thanks!

**Comment by cagnulein** [comment]
@brupec I should had fixed both in the 2.16.14 
I have a terrible flu, so I hope I did everything right.
I will upload it later today
Let me know!

**Comment by brupec** [comment]
ouch hope the flu doesn't last!

I'll let you know ;-) for the closed beta, do you know if it's linked to email ? so I maybe can get access sooner because last time google took like one week to approve the public beta one

**Comment by brupec** [comment]
or maybe you can send apk and I can install it ?

**Comment by cagnulein** [comment]
last time it took a long time because google was reviewing the watchos app,
now it should be quicker. I'm uploading it now, so it should be available
in 2 hours. Let me know if it doesn't work

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 set 2023 alle ore 11:50 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
Nop, the one I see in google is 2.16.13

**Comment by cagnulein** [comment]
damn google is still reviewing, you can use the trial version in the
meanwhile

https://github.com/cagnulein/qdomyos-zwift/suites/16577061165/artifacts/947059408

Il giorno mar 26 set 2023 alle 17:12 brupec ***@***.***> ha
scritto:

**Comment by brupec** [comment]
Just did, resistance level showed is now ok 1 to 24 but still not able to change it in the app. + and - does nothing. Am I doing right I should press + and - next to resistance level right? And the auto resistance needs to be disable or enable? Anyway I try both

**Comment by cagnulein** [comment]
yes you're doing it right.
Please share the debug log from this version
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 set 2023 alle ore 17:36 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
Here you go

[debug-Tue_Sep_26_17_40_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12729509/debug-Tue_Sep_26_17_40_05_2023.log)

**Comment by brupec** [comment]
allright, finger crossed ;-)

thanks to you, programming with flu is not easy

**Comment by cagnulein** [comment]
try this one
https://github.com/cagnulein/qdomyos-zwift/suites/16583185327/artifacts/947463728
last build for today :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 set 2023 alle ore 18:06 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
Rest good ;-)

I tried and unfortunately still nok.

Here is log for when you'll want to check (two, it recorded two I'm not sure one, in one of them I tried +/- in speed one and then moved on device in speed two and did same)
[debug-Tue_Sep_26_18_57_22_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12730142/debug-Tue_Sep_26_18_57_22_2023.log)
[debug-Tue_Sep_26_18_58_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12730144/debug-Tue_Sep_26_18_58_25_2023.log)

**Comment by cagnulein** [comment]
Ok, I'll check it out.
sorry if it's taking too long :(

Il giorno mar 26 set 2023 alle 19:02 brupec ***@***.***> ha
scritto:

**Comment by brupec** [comment]
no worries my friend, rest and get over that flu.

I'm using it as an excuse to get fat meanwhile :-p

**Comment by cagnulein** [comment]
ok new build is building
https://github.com/cagnulein/qdomyos-zwift/actions/runs/6324214226
Let me know if it's better, we're near!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 set 2023 alle ore 20:56 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
Hi my friend

Still same

[debug-Wed_Sep_27_13_55_36_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12738267/debug-Wed_Sep_27_13_55_36_2023.log)

**Comment by cagnulein** [comment]
this is an hard guy. ok today i have to go to the doctor, i will check it
asap
thanks

Il giorno mer 27 set 2023 alle 13:58 brupec ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/6325885157
the last one didn't handle in the way that it should be
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 set 2023 alle ore 13:59 cagnulein ***@***.***> ha
scritto:

**Comment by brupec** [comment]
[debug-Wed_Sep_27_16_15_39_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12739691/debug-Wed_Sep_27_16_15_39_2023.log)
not yet sir :-(

**Comment by brupec** [comment]
one thing I noticed, I don't know if it can help or not, is that when I start the machine, the resistance is at "0" in QZ.
but in the machine it always start to 1. I need to start rowing for QZ to show 1. Maybe it's normal, but prefer to notice in case it can help

**Comment by cagnulein** [comment]
yes that's normal :) i will check the log tomorrow
thanks!

Il giorno mer 27 set 2023 alle 18:46 brupec ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok there were differences also in the init phase. please try this one
https://github.com/cagnulein/qdomyos-zwift/actions/runs/6336065026
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 set 2023 alle ore 20:45 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
that's so strange, did you try also to set the resistance for example to 2
from the rower and then press the plus button from qz? I would like to
check if maybe only the shift from 1 to 2 is broken
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 set 2023 alle ore 14:17 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
yes, I always try at least 1 and 2, then + and - on each, and disable the
auto resist with top right icon

This time I tried with 1, 2 and 3

Le jeu. 28 sept. 2023 à 14:20, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
in the last log that you sent me the starting resistance was always 1 and
you push the button 7 times but always starting from resistance 1. That's
why i'm asking for a log where the starting resistance changes. it's just a
confirmation, thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 set 2023 alle ore 14:24 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
Yes on this last log I also tried to change from 2 and 3

Le jeu. 28 sept. 2023 à 14:26, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
I added other init frames that I thought that could be useless
https://github.com/cagnulein/qdomyos-zwift/actions/runs/6339076347
Let's see if it helps

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 set 2023 alle ore 14:29 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
does the trial works with external app or I need to wait the paid app release ?

**Comment by cagnulein** [comment]
@brupec great! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and i will unlock this version (then i will also push this one to google play too)
