### ISSUE TITLE
Speed and Incline not working on QZ Desktop app [BUG]

### ISSUE THREAD

**Issue by nickd86** [cagnulein/qdomyos-zwift#1675]
I have connected my Pro Form Pro 1000 treadmill to my Windows 10 PC via bluetooth.
I have installed the QZ desktop app which connects my treadmill to Zwift
I have turned on auto incline and speed, in both Zwift and treadmill settings of QZ.
When I open a workout in Zwift I start treadmill at 1mph however it doesn't sync with the speed of the workout (6mph) also the auto incline doesn't change to 1 as per workout.

I have enabled the debug log setting in QZ and recreated what I am doing.  Whilst when I change the speed and incline manually from Treadmill, Zwift updates, it is not done automatically.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
[debug-Tue_Sep_26_14_25_46_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12728353/debug-Tue_Sep_26_14_25_46_2023.log)

**Comment by cagnulein** [comment]
@nickd86 do you have 1920x1080 resolution in zwift?
#1581 @victorypoint @Jawaui  in case could help on this

**Comment by cagnulein** [comment]
@victorypoint the python script could be ok with 4k resolution?

**Comment by nickd86** [comment]
Is it possible to restore all settings within QZ and try to start again, I've been playing around trying different things but now it's not working at all

**Comment by Jawaui** [comment]
Hi, @nickd86 do you run in fullscreen mode? This is was victorypoint send me:
I confirmed that Zwift has to be in Windowed mode (full screen mode will not work). Then use a tool that puts games in 'borderless windows' mode (removes the game titlebar, border, and any other border elements). There's many solutions out there but I've tested a popular one called 'Borderless Gaming' - https://www.techspot.com/downloads/7061-borderless-gaming.html. It loads as a tray app and puts Zwift into borderless mode each time it is started. Please give this a try and let us know how it goes.
With this app it worked for me. Hope for you also!

**Comment by nickd86** [comment]
Hi Jawaui,

Thanks for your help.

I tried deleting the directory files and also changing screen resolution and to window instead of full screen.

Couldn't get it to work, reverted back to mobile app and that crashed half way through a run.

Don't know what to do, I haven't been able to get speed or incline to work and have spent all day and hours trying 😫

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by victorypoint** [comment]
@Jawaui, @cagnulein, I remember writing up some instructions on how to get auto-incline setup in QZ but can't find the previous post. Do you guys recall? The Windows QZ with Python has to be installed, environment variables must be added, and borderless gaming installed and setup for Zwift.

**Comment by victorypoint** [comment]
> @victorypoint the python script could be ok with 4k resolution?

Correct. OCR seems to only work reliably in Zwift Ultra (1440p) and 4K UHD (2160p) detail.

**Comment by cagnulein** [comment]
> Couldn't get it to work, reverted back to mobile app and that crashed half way through a run.

@nickd86 for the crash send me the debug log and I will check, qz can't definitely crash at all!

for the pc version follow the @victorypoint link

let me know

**Comment by Jawaui** [comment]
Hi @nickd86, did you change the path in window?
You must add 2 new entries to the Windows path (under system variables). For example, if QZ is installed at 'C:\Temp\qdomyos-zwift', the 2 new entries are:
- C:\Temp\qdomyos-zwift\python\x64
- C:\Temp\qdomyos-zwift\python\x64\Scripts\

**Comment by nickd86** [comment]
Hi there, 

I have reinstalled QT and connect my treadmill to PC via Bluetooth, but the two won't connect.

Please see debug report attached, can you please advise what I need to do?

[debug-Mon_Oct_2_15_07_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12783340/debug-Mon_Oct_2_15_07_05_2023.log)

[debug-Mon_Oct_2_15_08_44_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12783341/debug-Mon_Oct_2_15_08_44_2023.log)

Thanks
Nick

**Comment by cagnulein** [comment]
@nickd86 in these log you have a wrong setting: "ftms treadmill" must be set to disabled. Do this and restart QZ, let me know

**Comment by nickd86** [comment]
Hi Roberto,

I had already tried this; I've disabled and attached new logs.

QT doesn't register any treadmill speed/incline settings and nor does Zwift pick up the controller..

Treadmill is paired successfully via Bluetooth to PC.

[debug-Mon_Oct_2_19_11_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12785270/debug-Mon_Oct_2_19_11_37_2023.log)

See latest logs attached, any ideas?

**Comment by cagnulein** [comment]
@nickd86 i don't remember if you are using the msvc build. if not try this version and let me know 

https://github.com/cagnulein/qdomyos-zwift/suites/16579760991/artifacts/947253348

**Comment by cagnulein** [comment]
ok thanks, i will check the log tomorrow, 9pm here in italy . have a nice evening

**Comment by nickd86** [comment]
> ok thanks, i will check the log tomorrow, 9pm here in italy . have a nice evening

Ok no problem thank you have a nice evening too.

Keen to get this up and running, excited to start using Zwift :)

**Comment by nickd86** [comment]
Just to confirm it's a Pro Form Pro 1000 Treadmill

**Comment by cagnulein** [comment]
@nickd86 just to be sure: is it working ok on qz on android or ios?

**Comment by nickd86** [comment]
Yes works on my mobile (not auto incline or speed) but app works with zwift. But desktop not

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
@nickd86 one question: with the last msvc build did you try also to turn off the treadmill completely and try with qz? because I compared the log and it seems that with the last log the treadmill was in a strange state and it answered in a strange way. Are you able to do a clean log following this flow:
1) turn off the treadmill
2) turn on the treadmill
3) open qz


I would like to see if in this scenario, the QZ msvc build acts always strange or it's better.
Let me know!

**Comment by nickd86** [comment]
Hi Roberto, 

[debug-Tue_Oct_3_09_16_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12790124/debug-Tue_Oct_3_09_16_06_2023.log)

Have done this please see new logs

**Comment by cagnulein** [comment]
thanks @nickd86 so it's confirmed: the msvc build performs different on the bluetooth side (or at least the treadmill answers differntely from android/ios). I have to understand which is the difference.
I will let you know when I will be ready to test it again

**Comment by cagnulein** [comment]
can you try this?
https://github.com/cagnulein/qdomyos-zwift/suites/16818769599/artifacts/960601239

i'm trying to understand which is the culprit

thanks

Il giorno mar 3 ott 2023 alle 10:19 nickd86 ***@***.***> ha
scritto:

**Comment by nickd86** [comment]
Hi Roberto, 

Have installed new link but still no joy
[debug-Tue_Oct_3_19_42_21_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12795972/debug-Tue_Oct_3_19_42_21_2023.log)

**Comment by cagnulein** [comment]
yes unfortunately same error. i have to think about this :(

Il giorno mar 3 ott 2023 alle 20:46 nickd86 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
got finally the issue @nickd86 ! it's a stupid Microsoft compiler bug! I'm trying to fix it! I will let you know when I will be ready (hopefully later today)

**Comment by cagnulein** [comment]
actually i deleted that message because it wasn't it, anyway i'm building
another one following another lead. it should be ready any minute

Il giorno mer 4 ott 2023 alle 09:53 nickd86 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
another build is ready https://github.com/cagnulein/qdomyos-zwift/suites/16856683467/artifacts/962831054
thanks!

**Comment by cagnulein** [comment]
hi @nickd86 did you have a chance to try?

**Comment by nickd86** [comment]
Hi Roberto, no joy with this, installed and followed normal procedure, whilst it connected it didn't recognize speed/incline changes and wouldn't connect to Zwift.  Following that it kept crashing.

Please see new debug 
[debug-Thu_Oct_5_19_36_38_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12821933/debug-Thu_Oct_5_19_36_38_2023.log)

**Comment by cagnulein** [comment]
@nickd86 do you have another log, in this one i don't see any connection at all. i would like to see if I did some steps forward even if you don't see it from the outside 
thanks

**Comment by nickd86** [comment]
[debug-Tue_Oct_10_19_19_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12860591/debug-Tue_Oct_10_19_19_05_2023.log)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/146025674/b5604d14-06cf-4e5e-b152-d1b0ea0cf754)

**Comment by gmaroPL** [comment]
my log, auto speed, incline mode does not work
[debug-czw__paź_26_21_10_02_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13181804/debug-czw__paz_26_21_10_02_2023.log)

**Comment by cagnulein** [comment]
@gmaroPL the main issue is

`\"C:\\Users\\Lenovo\\Downloads\\qz\\output\\python\\x64\\lib\\site-packages\\paddle\\fluid\\core.py\", line 274, in <module>\r\n    from . import libpaddle\r\nImportError: DLL load failed while importing libpaddle: Nie mo?na odnale?? okre?lonego modu?u.\r\n"`

just to be sure, did you download the QZ windows version with python? 

following this https://github.com/cagnulein/qdomyos-zwift/issues/1581#issuecomment-1660774335
whichi is the output from `python --version` ?

let me know

**Comment by cagnulein** [comment]
@gmaroPL yes that's right. So which is the output from the command I wrote above?

**Comment by gmaroPL** [comment]
Python 3.10.11

**Comment by cagnulein** [comment]
can you please download this
https://github.com/cagnulein/qdomyos-zwift/files/12232359/qz-python-test.zip
and try to start the batch file on it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 27 ott 2023 alle ore 11:23 gmaroPL ***@***.***>
ha scritto:

**Comment by gmaroPL** [comment]
ok, I started it, what's next?

**Comment by cagnulein** [comment]
what's the output of the command?

**Comment by gmaroPL** [comment]
![IMG_1618](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/12fffe2c-0840-4d98-908b-d3d83bce7aab)
I click enter and the window disappears - nothing else happens

**Comment by cagnulein** [comment]
it should give you

```
- 2%
- Time taken: 1.6881608963012695 sec (this time will vary depending on your PC)
- Press any key to continue . . 
```

that's the issue.

Could you please test it from a command shell, go in that directory and run the batch file from there?

**Comment by gmaroPL** [comment]
![D93C4F26-7C46-4FB7-937B-C9B6C6459DA6](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/2f222208-90d1-45c8-a58e-04f7ffd82a52)

nothing else happens

**Comment by cagnulein** [comment]
@victorypoint any idea? it seems that @gmaroPL did the right installation of python

**Comment by victorypoint** [comment]
@gmaroPL, @cagnulein, we should confirm that the Python environment variables have been set correctly.

You must add 2 new entries to the Windows path (under system variables). For example, if QZ is installed at 'C:\Temp\qdomyos-zwift', the 2 new entries are:
- C:\Temp\qdomyos-zwift\python\x64
- C:\Temp\qdomyos-zwift\python\x64\Scripts\

Then reboot and retry getincline.bat.

**Comment by gmaroPL** [comment]
Can you describe what I should do exactly?

**Comment by cagnulein** [comment]
@gmaroPL the images that i attached on messenger

**Comment by gmaroPL** [comment]
ok ;)

**Comment by cagnulein** [comment]
@gmaroPL download this https://raw.githubusercontent.com/cagnulein/qdomyos-zwift/Windows-PATH-batch/src/windows/setup.bat and place it where you have the qdomyos-zwift.exe (at the same LEVEL, is important!)
then start it as an administrator and reboot the PC
then start again the getincline.bat and show the output here

**Comment by cagnulein** [comment]
#1736

**Comment by gmaroPL** [comment]
![Przechwytywanie](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/61c65fab-4182-4c0f-be19-7febb2cfdd6b)

**Comment by cagnulein** [comment]
what does nie mo means?

Il giorno sab 28 ott 2023 alle 14:13 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
I don't think it can open ??

**Comment by cagnulein** [comment]
did you run as administrator? is it the output from  the new script or of
the getinclune one?

Il giorno sab 28 ott 2023 alle 14:19 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
result  getinclune

**Comment by cagnulein** [comment]
did you restart the pc after starting my batch?

Il giorno sab 28 ott 2023 alle 14:24 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
Yes, I ran it twice

**Comment by cagnulein** [comment]
i'm riding now, i will check it later

Il giorno sab 28 ott 2023 alle 14:26 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
ok

**Comment by cagnulein** [comment]
in a terminal run this command

echo %PATH%

Il giorno sab 28 ott 2023 alle 14:28 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
![Przechwytywanie2](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/33eda16e-890e-4a26-a589-e43def4ce8b7)

**Comment by cagnulein** [comment]
the problem is that you didn't put the new script inside the output folder
of qz
put there and re run as administrator

Il giorno sab 28 ott 2023 alle 15:41 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
What I should do now?

**Comment by victorypoint** [comment]
Hi @gmaroPL. Could you try this? Go to the Environment Variables window again (Win+R then enter "SystemPropertiesAdvanced"). From this screen, click Environment Variables button at the bottom, then you will see 2 areas - User variables at top, and System variables at the bottom. Select PATH in the System variables area and click Edit button. You want to see 2 entries in the list. For example, my QZ is installed at "C:\Temp\qdomyos-zwift". So the 2 entries should be:

- C:\Temp\qdomyos-zwift\python\x64
- C:\Temp\qdomyos-zwift\python\x64\Scripts\

Where is your QZ installed? We want to make sure this folder is before the python folders. Once you have these 2 entries correct, make sure there are no incorrect ones in the list that contain "python".

Also, in the User variables area, also make sure there are no PATH entries that contain "python".

Reboot your PC, run echo %PATH% again, and let us know the output. Also try getincline.bat to see if it works.

**Comment by cagnulein** [comment]
> What I should do now?
> 
> 

put my batch inside the output folder and run it from administrator

**Comment by gmaroPL** [comment]
![Przechwytywanie3](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/3988d46b-8625-47b1-b5bc-d152b56421cf)

I changed the location of the directories
![Przechwytywanie4](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/eb669097-d006-412d-9e12-4d91cfe68f58)

**Comment by cagnulein** [comment]
ok so do you have qz on that folder now? yesterday was a different one. if
so you can try to run getincline again

Il giorno sab 28 ott 2023 alle 16:56 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
I launched it  getincline

![Przechwytywanie5](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/aaa2ffca-cdc0-418e-a225-3e1e67309a84)

**Comment by gmaroPL** [comment]
![Przechwytywanie6](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/136a5bc6-c650-4653-9dfd-7e2708eb5040)

**Comment by victorypoint** [comment]
@gmaroPL, thank-you for testing this and posting the screenshots. @cagnulein, I just installed and tested same build (https://github.com/cagnulein/qdomyos-zwift/suites/16818769599/artifacts/960601239). In my case, it appears the python install is incomplete. I get this error and confirmed missing python files:

The code execution cannot proceed because python310.dll was not found. Reinstalling the program may fix this problem.

**Comment by cagnulein** [comment]
thanks @victorypoint actually i didn't change anything in the yaml file here on github. i will compare the builds on monday.
Thanks!

**Comment by gmaroPL** [comment]
OK

**Comment by gmaroPL** [comment]
what should I do ?

**Comment by cagnulein** [comment]
@gmaroPL replace your current qz folder with the one in the link. please use the same path!

**Comment by gmaroPL** [comment]
getincline.bat result
![Przechwytywanie6](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/90db5852-bc7d-42c9-8f6c-19f1bbfed26c)

**Comment by victorypoint** [comment]
@cagnulein, latest build is good. Python works.

@gmaroPL, it looks like your QZ install is still not right. Please make sure you've unzipped the latest version from the link above and placed it in your c:\qz folder (or wherever your QZ is installed). Also, please run this so we can confirm your PATH environment:

echo %PATH:;=&echo.%

**Comment by cagnulein** [comment]
thanks for the confirmation @victorypoint , that's very important to me!

**Comment by gmaroPL** [comment]
![Przechwytywanie8](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/b0d9648f-f1c7-4225-94d5-91c00d938a5c)

**Comment by gmaroPL** [comment]
![Przechwytywanie8](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/314dc948-7077-440b-b1c4-033a69ef5a20)

**Comment by gmaroPL** [comment]
I corrected the path
![Przechwytywanie10](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/51f4a477-d597-4248-a450-d13201fa76e2)

**Comment by cagnulein** [comment]
I still see the same path. So do you confirm that you have QZ installed on c:\qz\output\ ?
could you please make a screenshot of that folder?

**Comment by gmaroPL** [comment]
![Przechwytywanie11](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/a6e22921-8fa9-4b6f-b007-a0ec9e80336b)

getincline.bat

**Comment by gmaroPL** [comment]
c:\qz\output\

![Przechwytywanie12](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/cc59a335-3695-4915-be01-b2b58355ce74)

**Comment by cagnulein** [comment]
ok @gmaroPL qz path is right. Are you 100% sure that you replace the new version that I sent today? in order to be sure you can delete the current one and download the new one again

**Comment by victorypoint** [comment]
@gmaroPL, I'll reproduce your QZ install folders and path and see if there's a problem. Standby..

**Comment by gmaroPL** [comment]
ok ;)

**Comment by gmaroPL** [comment]
ok,moment

**Comment by gmaroPL** [comment]
![Przechwytywanie13](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/52542d3e-364a-469d-9db9-aea69e8be6fd)

**Comment by gmaroPL** [comment]
![Przechwytywanie14](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/f2eb7703-32da-4f21-8060-13c7b22ebf20)

**Comment by gmaroPL** [comment]
I can provide you with a computer - Anydesk program
this computer is only for qz

**Comment by gmaroPL** [comment]
![Przechwytywanie15](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/6f8e9b60-c0b4-4d09-bd98-2b76944addd5)
![Przechwytywanie16](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/df27c8d4-dd5e-4903-8f95-2298e7671edf)
![Przechwytywanie17](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/1ea0e1b3-0c01-48ce-92eb-23f2e523cc95)

**Comment by victorypoint** [comment]
@gmaroPL, ok this is strange. I get:
pip 23.3.1 from C:\qz\output\python\x64\lib\site-packages\pip (python 3.10)

Whereas you get:
pip 23.2.1 from C:\qz\output\python\x64\lib\site-packages\pip (python 3.10)

So you have a slightly older version of pip. Also a few other packages in your list have older version numbers than me which may be causing the problem. I wonder if your QZ got updated correctly with the last provided link? Also make sure all other installs of QZ are removed.

**Comment by gmaroPL** [comment]
let's start from the beginning
What should I install? Provide links.
I will do this on another new computer.

**Comment by victorypoint** [comment]
@gmaroPL, sure. 

- Download and install QZ with Python Windows package - see @cagnulein's link above
- Add 2 new entries to the Windows path (under system variables). For example, if QZ is installed at 'c:\qz', the 2 new entries are:
  - c:\qz\python\x64
  - c:\qz\python\x64\Scripts\
- Reboot your PC. Then at a command prompt execute:
  - echo %PATH:;=&echo.%
  - python -V
  - python -m pip -V
  - python -m pip list
- Include output of all commands above so we can confirm
- Test QZ OCR conversion with qz-python-test script

**Comment by gmaroPL** [comment]
![Przechwytywanie](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/986f36fb-407a-4057-90e1-916029c05f12)
![Przechwytywanie1](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/2c81cea7-b8bd-4dba-b95f-261e584dc11d)

**Comment by victorypoint** [comment]
@gmaroPL, very interesting! Please unzip the attached getincline.py and replace the old one, then re-run getincline.bat and tell us the output.

[getincline.zip](https://github.com/cagnulein/qdomyos-zwift/files/13209436/getincline.zip)

**Comment by gmaroPL** [comment]
change effect

![Przechwytywanie](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/5c929ef6-a35b-421a-800e-f89d71d29870)

**Comment by victorypoint** [comment]
Ok, thanks @gmaroPL. We really appreciate you helping us debug the problem. Can you please run this from the command-line and retry getincline.bat. You shouldn't have to reboot this time.

python -m pip install --force-reinstall paddlepaddle==2.4.2

**Comment by gmaroPL** [comment]
![Przechwytywanie](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/931ad326-f8ec-49da-894e-cba8527b9699)

![Przechwytywanie1](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/a8ca32a3-7eb5-4cd3-89f0-3f929f3305f8)

**Comment by victorypoint** [comment]
@gmaroPL, ok good. What happens when you try getincline.bat again?

**Comment by gmaroPL** [comment]
![Przechwytywanie](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/a400b722-c2d7-4eae-be2c-f67a9525060c)

**Comment by victorypoint** [comment]
@gmaroPL, I'll have to duplicate this on a new install of Windows. Can you confirm if you're using Windows 10 or 11?

**Comment by gmaroPL** [comment]
Windows 10

**Comment by victorypoint** [comment]
@gmaroPL, okay I did a clean install with Windows 10 and got it to work on the 1st time. So we need to figure out what's going on with your installs. Maybe all the files didn't get unzipped or some got corrupted during unzipping? You've reinstalled Paddlepaddle so I wonder if the PaddleOCR component is missing files or corrupt. Try reinstalling it from the command prompt and retry getincline.bat:

 python -m pip install "paddleocr>=2.0.1"

**Comment by gmaroPL** [comment]
tell me what link I should use to unpack the Windows version!!!!

I will unpack and what next?

**Comment by victorypoint** [comment]
@gmaroPL, try re-downloading from the last link provided. It's the same one I used to test with. Replace the old install and see what happens.

https://github.com/cagnulein/qdomyos-zwift/suites/17739244097/artifacts/1015871000

**Comment by gmaroPL** [comment]
ok, I'm doing it now

![Przechwytywanie](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/4308d5fa-9c05-4309-9e98-6869302be9f1)

**Comment by cagnulein** [comment]
maybe something about the localization?

Il giorno mar 31 ott 2023 alle 20:00 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
![Przechwytywanie](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/d7b5465a-dcfd-4ecc-a119-e3864894f24f)

**Comment by victorypoint** [comment]
@gmaroPL, could you post your system specs? Settings - System - About

**Comment by gmaroPL** [comment]
how to do it?

**Comment by gmaroPL** [comment]
![Zrzut ekranu 2023-10-31 202310](https://github.com/cagnulein/qdomyos-zwift/assets/148910480/ce16b643-4f1f-4b58-90ae-6d93922753e0)
Windows 11 - virtual machine for MacBook :D

**Comment by victorypoint** [comment]
@gmaroPL, it's working! So that's in a virtual machine for MacBook? And the other attempts were done with real Windows PCs?

**Comment by victorypoint** [comment]
@gmaroPL, good! What did you do to get it to work?

**Comment by gmaroPL** [comment]
it works on a laptop with windows 10, what now???

**Comment by victorypoint** [comment]
@gmaroPL, this is excellent. So now you can try QZ on your Windows 10 laptop with your x32i treadmill.

**Comment by gmaroPL** [comment]
ok, I'll go check it out

**Comment by gmaroPL** [comment]
what options should I set in the program to use zwift workout antitime/

**Comment by cagnulein** [comment]
the zwift workout only in qz

Il giorno mar 31 ott 2023 alle 20:57 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
?

**Comment by cagnulein** [comment]
in qz, under zwift settings, the workout one

**Comment by gmaroPL** [comment]
I set training mode but I still don't respond

**Comment by cagnulein** [comment]
please attach a debug log
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Il giorno mar 31 ott 2023 alle 21:23 gmaroPL ***@***.***> ha
scritto:

**Comment by gmaroPL** [comment]
Today is the end of the tests, I'm tired - thank you for your help

I will prepare a log file.

**Comment by cagnulein** [comment]
@gmaroPL any news?

**Comment by gmaroPL** [comment]
> @gmaroPLjakieś wieści?

I didn't test further
I will test today and tomorrow and in the following days - I will write information
