### ISSUE TITLE
WahooRGT  not chaging resistace accordibg to slope via qz on my proform tdf costco bike

### ISSUE THREAD

**Issue by MFR100** [cagnulein/qdomyos-zwift#1679]
i did the settings asroberto suggested, but the automatic change of resistance is not happening,
** to reproduce **
1. started de bike, then qz, and verified the sensors were sending information like cadence,
2. started Wahoo rgt free app , selected just ride, and then a free ride with slopes
3. set the starting position close to end of downhill to uphill transition and continued pedaling. 
4. the bike resistance from the beginin was showing the lowest level of 1 in the lcd didplay
5. i went from negative slope to  +7.5 slope, but the resistance did not change, stayed at 1 all the time

**Expected behavior**
resistance on the bike should change to higher values when i go uphill according to the route terrain

**Screenshots**
none

**Desktop (please complete the following information):**
na

**Smartphone (please complete the following information):**
 - Device: samsung galaxy tab S4
 - OS: Android
 - Version 10
[debug-Thu_Sep_28_18_18_23_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12754433/debug-Thu_Sep_28_18_18_23_2023.log)
[debug-Thu_Sep_28_18_18_23_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12754447/debug-Thu_Sep_28_18_18_23_2023.log)
[debug-Wed_Sep_27_18_33_32_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12754448/debug-Wed_Sep_27_18_33_32_2023.log)
[debug-Wed_Sep_27_18_45_51_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12754449/debug-Wed_Sep_27_18_45_51_2023.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@MFR100 very stupid issue: you just need to disable the zwift erg mode setting  in QZ :)
let me know!

**Comment by MFR100** [comment]
I disabled the zwift optio but still wahoo does not adjust the resistance   2 new logs attached
[debug-Fri_Sep_29_17_13_52_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12772039/debug-Fri_Sep_29_17_13_52_2023.log)
[debug-Fri_Sep_29_17_20_29_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12772040/debug-Fri_Sep_29_17_20_29_2023.log)
[debug-Fri_Sep_29_17_13_52_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12772047/debug-Fri_Sep_29_17_13_52_2023.log)

**Comment by MFR100** [comment]
Sorry 9ne log file did nnot upload try again this should be f8ne
[debug-Fri_Sep_29_17_27_54_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12772057/debug-Fri_Sep_29_17_27_54_2023.log)

**Comment by MFR100** [comment]
Roberto, I switched off that setting, but I got the same result, no changes on the bike resistance. I added 2 additional logs to the ticket, sorry one of the files was just qz running while I reviewed settings but the last one on a separate comment should be fine.

Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
now you have the zwift force resistance disabled in the experimental
settings. you have to enable it
let me know

Il giorno sab 30 set 2023 alle 00:26 MFR100 ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
Roberto
I tried with it enabled and disabled and got the same results, I can see speed cadence, etc I wahoo and in QZ but the change of slope does not change the resistance on the bike.
I did the same short segment starting in negative slope and nothing changed in terms of resistance when it started to go up from negative to plus 7.
I attached the most recent log and a picture of the bike lcd showing resistance of 1 and the screen of the tablet showing wahoo incline and the tinny picture in picture from qz

Also on a side note I stalled my Whoosh on the same tablet but it did not detected any bike , do i have to change settings in QZ to make it work? It is the first time using that app so I don't know if it has its own settings

Thanks
________________________________

**Comment by cagnulein** [comment]
@MFR100 i can't see the attachments, you have to attach on the github web interface 

thanks

**Comment by MFR100** [comment]
Here they are
![PXL_20230930_143132757](https://github.com/cagnulein/qdomyos-zwift/assets/146393526/12ca5549-0f6d-4728-b184-5eeaec25aad8)
[debug-Sat_Sep_30_10_27_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12774965/debug-Sat_Sep_30_10_27_31_2023.log)

**Comment by cagnulein** [comment]
for my whoosh the issue is that you have virtual
ifit enabled in the experimental settings. disabled it

i'm checking the wahoo issue instead

Il giorno sab 30 set 2023 alle 17:01 MFR100 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
for wahoo rgt could you please try to join the beta: maybe I already fixed
this issue https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift
you have to see version 2.16.13 of qz
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 set 2023 alle ore 17:17 cagnulein ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
Joined the beta and followed the same steps, still the same result 
Not 8sure if it is important  but if I try to use the + or - on the resistance tile I QZ, they don't change anything either. Here is  other log file for your reference.
[debug-Sat_Sep_30_13_32_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775238/debug-Sat_Sep_30_13_32_05_2023.log)

**Comment by cagnulein** [comment]
ok thanks i will check it tomorrow

Il giorno sab 30 set 2023 alle 19:40 MFR100 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
one question: with the current setup, but without opening wahoo, are you
able to change the resistance from qz tile?

Il giorno sab 30 set 2023 alle 20:14 cagnulein ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
No, it. seems QZ is stuck on whatever it is set in the bike

Miguel Rodriguez

________________________________

**Comment by MFR100** [comment]
Forgot to mention if I manually change the resistance on the bike panel, QZ shows the right value, si from the bike to QZ  works fine, buy from qz or other app to the bike does not change.

Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
hah ok i thought it was working on with zwift.
ok let me check the debug log tomorrow so
thanks

Il giorno sab 30 set 2023 alle 21:20 MFR100 ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
As far as I recall it worked, but my zwift expired more than 6 months ago and I have been riding outside all this time. I thought it worked fine last time I used it around March, but I might be wrong. That is why I am trying the free wahoo rgt and I also want to try my

Miguel Rodriguez


________________________________

**Comment by MFR100** [comment]
Sorry sent it before finishing by mistake ..
That is why also want to try MyWhoosh but I haven't been able to connect the bike to it.
MyWosh says scanning for bike but then it cannot find it, so I have now even being able to find if MyWhoosh is able to change the resistance


Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
ok it was about this one https://github.com/cagnulein/qdomyos-zwift/issues/452
I'm still checking!

**Comment by cagnulein** [comment]
@MFR100 if you disable the "Tour de France CLC" setting and restart QZ, can you change the resistance from QZ? If not let me know

**Comment by MFR100** [comment]
Roberto good news!! That did the trick. I disabled CLC, and I was able to change the resistance from the QZ UI , then I started Wahoo, Flanders in the same end of downhill and then going up, and it automatically increase the resistance.  On my bike that max resistance is 16 and in a part of the uphill it went all the way to 16.  It wasn't the highest Lipe, so is there a way to tune it down?? Like a percentage or something so I can do routes and workouts closer to what my aging body is able to do?

And again just  the other question regarding MyWhoosh , I I have not been able to make MyWhoosh see the bike, it just says scanning and no device found. Is there a setting or something in QZ that allows me to use my bike with MyWhoosh app?

Thanks alot for all your patience and support


Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
great news @MFR100 
for the resistance, turn down the zwift resistance offset. this value is the resistance lev that you feel like a flat road

for my whoosh, are you using 2 devices? 1 for qz and 1 for my whoosh? did you disable the virtual ifit setting?

maybe push here another fresh log from qz so i will check if your current settings are right

**Comment by cagnulein** [comment]
that's unfortunate :( but rgt isn't inside the systm app now?

Il giorno lun 2 ott 2023 alle 21:52 MFR100 ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
Here is the new log, since you wanted just the settings to verify why MyWoosh does  ot see the bike, I did not open other app, just QZ.  
To answer your question I use only one device, my tablet running qz and connected to the bike via Bluetooth and the training g app in the same device.  With all other apps if I started qz first they could detect the bike , but MyWoosh does not, so that is why I think is a setting or something  else.
Thanks

**Comment by cagnulein** [comment]
@MFR100 i didn't check the log yet but there is an issue on your setup: with my whoosh you need 2 devices for sure, 1 for qz and 1 for my whoosh. is it your setup?

**Comment by MFR100** [comment]
Hi Roberto, no my setup is just one tablet, so do I have to install QZ on phone or other device? If so, since I already have it installed on my tablet, do I have to.purchase other license of QZ?

Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
no you don't have to purchase another qz license.
yes you have to install zwift on another device, my whoosh didn't implement
the one device only feature

Il giorno mar 3 ott 2023 alle 13:28 MFR100 ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
Now I am confused, do I need to install zwift in other device? Or MyWhoosh? I installed the apps on the tablet because it is easier to see and place a tablet in front of the bike. So I would need to install QZ on the phone.

Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
i mean my whoosh sorry. if you have android/ios on both devices you don't
have to pay again for qz

Il giorno mar 3 ott 2023 alle 13:34 MFR100 ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
Yes I can use an older android phone that I have to install QZ on it and the android tablet to run MyWhooz, is there a guide or a video or something with the recommended setting for the 2 device setup?

Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
simply open qz first,  connect it to your fitness device and then open my
whoosh on the other device looking for the phone
just this
Let me know

Il giorno mer 4 ott 2023 alle 00:32 MFR100 ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
Roberto, I have the qz app working on an android phone and connected to my bike, but when I open My Whoosh it just shows me a dialog asking me to connect , I select the only option  but it never does. I tried ANT+ disabled or a able in Whoosh settings but made no difference  Some screenshots attached.
How do I tell MyWhoosh to connect t to my phone's QZ?
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
I never used my whoosh so i don't know how to this,but it should work as
zwift

anyway
1) is your phone named as "bike"? if not, rename it and reboot it
2) if it doesn't work send me a fresh debug log so i can check it

Il giorno mer 4 ott 2023 alle 20:55 MFR100 ***@***.***> ha
scritto:

**Comment by T890579** [comment]
I did name the phone as "bike", rebooted and tried again starting qz on the phone, and the started my whoosh on the tablet . Same thing mywhoosh did not find any bike  attaching the log from the phone  qz

**Comment by cagnulein** [comment]
@T890579 you have the virtual ifit setting enabled in the experimental settings. Disable it and restart QZ, that's the issue

**Comment by cagnulein** [comment]
hi @MFR100 please attach a fresh debug log so i can check your current scenario

**Comment by MFR100** [comment]
I changed the setting and did not work with MyWoosh, then I verified it still works with Wahoo.  Log attached

**Comment by cagnulein** [comment]
@MFR100 i don't see the log

**Comment by MFR100** [comment]
Sorry github is behaving weird on my phone so I have to write the comment , save, and then attach the files. They are there now

**Comment by cagnulein** [comment]
got another issue in setting: you have the peloton cadence sensor enabled. disable it and restart qz
let me know

**Comment by MFR100** [comment]
This was the solution, it is working now thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MFR100** [comment]
Thanks a lot for your support

**Comment by cagnulein** [comment]
glad to hear this!

Il giorno sab 7 ott 2023 alle 02:00 MFR100 ***@***.***> ha
scritto:
