### ISSUE TITLE
Debug Log- Lifespan X41 elliptical cross trainer

### ISSUE THREAD

**Issue by Intellirump** [cagnulein/qdomyos-zwift#1804]
Hi again Roberto

I hope this finds you well.

please see attached debug Log as requested for issue : no metrics displaying in QZ App. Please let me know if I can be of any more help.

thanks
Nicole
[debug-Wed_Nov_22_20_14_17_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13438094/debug-Wed_Nov_22_20_14_17_2023.log)

**Comment by cagnulein** [comment]
found the issue! i'm fixing it! let's continue here! #1799

**Comment by cagnulein** [comment]
@Intellirump the problem is that you didn't set the iconsole_elliptical new setting in QZ. Please enable it and restart QZ
Let me know!

**Comment by Intellirump** [comment]
You did too! Do U mean this setting?(see attached photo) I'm a bit confused
it says iConcept?

**Comment by cagnulein** [comment]
i don't see the photo, you have to upload to github directly. anyway yes, iconcept it's right because it's the iconcept protocol that handle your device ;)

**Comment by Intellirump** [comment]
Ok so I think I am in the right place. I slid the red tab across . Saved
and restarted the app. Still no metrics displaying when I click start and
move on the machine.

**Comment by Intellirump** [comment]
![PXL_20231122_111555740](https://github.com/cagnulein/qdomyos-zwift/assets/151582306/b6e330e9-c142-41ce-b3ea-c45a92ca1926)

**Comment by cagnulein** [comment]
please share me a debug log in this context, thanks

**Comment by Intellirump** [comment]
![PXL_20231122_105957888](https://github.com/cagnulein/qdomyos-zwift/assets/151582306/3d2bc524-61ed-4b88-8b04-90da34e08bf4)

Do I need to select this in advanced settings? Or leave it on disabled

**Comment by Intellirump** [comment]
Will do 👍🏼

**Comment by Intellirump** [comment]
[debug-Wed_Nov_22_21_24_15_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13438747/debug-Wed_Nov_22_21_24_15_2023.log)

**Comment by cagnulein** [comment]
stupid me, fixed, it's building
https://github.com/cagnulein/qdomyos-zwift/actions/runs/6957400908

Il giorno mer 22 nov 2023 alle 12:36 Intellirump ***@***.***>
ha scritto:

**Comment by Intellirump** [comment]
Not stupid 🙂

How did it go?

**Comment by cagnulein** [comment]
@Intellirump did you try the last build?

**Comment by Intellirump** [comment]
can u please let me know what to click on?  i tried guessing but didn't
take me anywhere. There are a lot of links.

thanks

**Comment by cagnulein** [comment]
sure this one
https://github.com/cagnulein/qdomyos-zwift/suites/18411304424/artifacts/1066943127

Il giorno gio 23 nov 2023 alle 08:10 Intellirump ***@***.***>
ha scritto:

> can u please let me know what to click on? i tried guessing but didn't
> take me anywhere. There are a lot of links.
>
> thanks
>

**Comment by Intellirump** [comment]
for some odd reason my tablet will not let me download this new one. I have even turned harmful app detection off in settings to see if it fixes it but no. I click 'install anyway' then I get the message 'app not installed'.  plz see attached screen shots.

sorry to be a pain. any ideas appreciated
![Screenshot_20231123-195257_Package installer](https://github.com/cagnulein/qdomyos-zwift/assets/151582306/59751f82-5338-4aea-a93d-da11ab2a8981)
![Screenshot_20231123-195331_Google Play Store](https://github.com/cagnulein/qdomyos-zwift/assets/151582306/a1ee3baf-38dd-4d28-a707-ef8bcef4fcfd)
![Screenshot_20231123-195341_Google Play Store](https://github.com/cagnulein/qdomyos-zwift/assets/151582306/c63b3169-599f-4f6d-8085-ba7e6b1bb7f9)

**Comment by cagnulein** [comment]
you have to uninstall first the play store one and then install this one
don't worry you will be able to install the play store again without paying
again

Il giorno gio 23 nov 2023 alle 11:00 Intellirump ***@***.***>
ha scritto:

**Comment by Intellirump** [comment]
ok followed this uninstalled old one, and installed the new one and opened fine. it shows my machine is found and I ensured the elliptical option in iconcept setting was enabled. still no metrics are displaying when I press start and hop on the machine.

One difference I note compared to an app such as kinomaps or fitlink is that my machines screen will read 'BT CONNECTED' and the metrics display instead on the app instead of machine. Is the goal to try get  my machine to also connect in this way so the display on the machine doesn't read a thing and all the metrics are viewed in the app? is it possible that some machines even if they have Bluetooth, won't always work? I'm happy to keep trying different solutions but if u think its wise to call the quits then that's okay too !

**Comment by cagnulein** [comment]
please attach always a debug log otherwise I can't help you. Don't worry I will make it work, I just need to do same test & try since I can't test my code alone and I need you for this :)

**Comment by Intellirump** [comment]
[debug-Thu_Nov_23_21_21_21_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13449284/debug-Thu_Nov_23_21_21_21_2023.log)

cheers =)

**Comment by cagnulein** [comment]
the problem here is that you forgot to enable back the iConsole Elliptical
setting
enable it and restart
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 23 nov 2023 alle ore 12:27 Intellirump <
***@***.***> ha scritto:

**Comment by Intellirump** [comment]
What the. That is so weird. I actually distinctly recall enabling it and
restarting. I double checked after I restarted that it was still in enabled
position. I'll do it again and send thru

**Comment by cagnulein** [comment]
you enabled the iconcept one not the iconsole :)

Il giorno gio 23 nov 2023 alle 22:20 Intellirump ***@***.***>
ha scritto:

**Comment by Intellirump** [comment]
Riiighht I have just found this new option. I'll get back to U soon 🙂

**Comment by Intellirump** [comment]
hi , we are getting close, so my machine now displays BT CONNECTED for the first time after enabling iconsole elliptical. however, the metrics still not reading when press start and hop on machine. plz see attached debug
[debug-Fri_Nov_24_07_32_58_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13453562/debug-Fri_Nov_24_07_32_58_2023.log)
![PXL_20231123_212848762](https://github.com/cagnulein/qdomyos-zwift/assets/151582306/c311a137-bf31-4459-a85f-dbc211199ee5)

**Comment by cagnulein** [comment]
thanks i will check tomorrow!

Il giorno gio 23 nov 2023 alle 22:45 Intellirump ***@***.***>
ha scritto:

**Comment by Intellirump** [comment]
👍🏼👍🏼

**Comment by cagnulein** [comment]
@Intellirump new build in progress https://github.com/cagnulein/qdomyos-zwift/actions/runs/6978037129
In 30 minutes, at the bottom of this page you will see the new apk
Let me know!

**Comment by Intellirump** [comment]
hi Roberto thanks for sending through. followe usual steps, uninstalled old QZ installed new one, enabled console, my machine reads BT CONNECTED but no metrics on QZ , attached debug, cheers
[debug-Fri_Nov_24_19_31_46_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13457453/debug-Fri_Nov_24_19_31_46_2023.log)

**Comment by cagnulein** [comment]
thanks @Intellirump 
now the parser is working but the trainer is sending always 0.
I'm wondering if you have to press start somewhere in the console? is it possible?
kinomap works right? if you want you can sniff the log from kinomap so I can see if they do something peculiar https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Let me know!

**Comment by Intellirump** [comment]
My machine won't allow me to press start, everything is disabled on it when it connects to a compatible app and the app takes control. There is no option to over ride this that I can see, no buttons to press. It certainly is strange. It seems like it's strictly pre wired to only connect with these certain apps like Kinomap and Fitlink which it was advertised with...I can't pair it with my phone or tablet alone, needs an app.

I have attached a Kinomap snoop log .
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13458193/btsnoop_hci.log)

🙂

**Comment by cagnulein** [comment]
graet I will check this in 3 hours!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 nov 2023 alle ore 11:54 Intellirump <
***@***.***> ha scritto:

**Comment by Intellirump** [comment]
Cheers , no rush 😀

**Comment by Intellirump** [comment]
👍🏼 🙂🤞🏼

**Comment by cagnulein** [comment]
@Intellirump ok I did it. I did a lot of modification, so it will be normal if everything will not work at first. Maybe we need several version to stabilize everything. The build is building here https://github.com/cagnulein/qdomyos-zwift/actions/runs/7003519088
You will see the link to download the new apk when the build is done, at the bottom of the page ( you have to download the "fdroid-android-trial" one)

Let me know!

**Comment by cagnulein** [comment]
new link https://github.com/cagnulein/qdomyos-zwift/actions/runs/7003685088

**Comment by cagnulein** [comment]
sorry new link again https://github.com/cagnulein/qdomyos-zwift/actions/runs/7003942710

**Comment by cagnulein** [comment]
sorry last one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7004018374

**Comment by Intellirump** [comment]
Hi Roberto , thanks heaps for the effort. I'll try this and get back to you
asap.

Nicole

**Comment by Intellirump** [comment]
hey  sorry for the delay on this!

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13512631/btsnoop_hci.log)

**Comment by cagnulein** [comment]
hi @Intellirump no problem, but I need a debug log not a hci one, thanks :)
are you feeling any better now?

**Comment by cagnulein** [comment]
mmm it doesn't seems the right QZ version, could you please try to download this (remember always to uninstall the previous and set again the iconsole_elliptical setting). thanks

https://github.com/cagnulein/qdomyos-zwift/suites/18629810827/artifacts/1083255735

**Comment by Intellirump** [comment]
[debug-Fri_Dec_1_08_04_21_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13520649/debug-Fri_Dec_1_08_04_21_2023.log)
[debug-Fri_Dec_1_07_52_39_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13520650/debug-Fri_Dec_1_07_52_39_2023.log)

Hi again Roberto, sorry to be a pain. I managed to find it somehow. Hope this is right this time. I did delete old version. And installed new one, ensuring iconsole eliptical is selected. Then ran QZ whilst recording debug with machine on. 

Thanks,
Nicole

**Comment by cagnulein** [comment]
perfect I fixed the initialization
https://github.com/cagnulein/qdomyos-zwift/suites/18662269403/artifacts/1085690684
Let me know how it goes with this
THanks, we are near!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 dic 2023 alle ore 05:26 Intellirump <
***@***.***> ha scritto:

**Comment by Intellirump** [comment]
Thank you, here is another debug. Still not showing BT connected like it did that time, no metrics. I have faith lol🕯️🙂

[debug-Fri_Dec_1_21_26_56_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13525997/debug-Fri_Dec_1_21_26_56_2023.log)

**Comment by cagnulein** [comment]
new version
https://github.com/cagnulein/qdomyos-zwift/suites/18670974335/artifacts/1086309718

finger crossed

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 dic 2023 alle ore 12:34 Intellirump <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@Intellirump it's very strange: i'm sending the same kinomap frames but the elliptical is sending me different answers. it drives me crazy. Could you try to disable the virtual bluetooth device setting in the experimental settings and restart qz? I would like to see if it makes any difference in the debug log.
Don't you still see the BT CONNECTED info on the elliptical, right?
Thanks

**Comment by Intellirump** [comment]
[debug-Mon_Dec_11_18_09_23_2023 (1).log](https://github.com/cagnulein/qdomyos-zwift/files/13632687/debug-Mon_Dec_11_18_09_23_2023.1.log)
 
Hii I followed your instructions, disabled that setting as mentioned and did another debug.

And no, there is nothing on the screen on my machine indicating BT Connected.  I suspect this is part of the issue.. It only displayed that at one point along the track when I thought we were getting closer but the next version it didn't say BT Connected anymore/ since.

**Comment by cagnulein** [comment]
Ok! so for sure also this setting must be disabled for your trainer because something changed in the log. I also fixed other 2 things. I'm building now, I will provide you another version in an hour
Thanks!

**Comment by cagnulein** [comment]
@Intellirump done! https://github.com/cagnulein/qdomyos-zwift/suites/18927774393/artifacts/1105693483

remember to set the iconsole_elliptical setting and disable the virtual bluetooth device.
Let me know

**Comment by Intellirump** [comment]
Hi, thanks, I have deleted old version and reinstalled this new version, tried this again per instructions above enabling iconsole setting and disabling virtual Bluetooth settings.  No luck sorry. Still not showing BT connected. 
[debug-Tue_Dec_12_20_20_21_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13647067/debug-Tue_Dec_12_20_20_21_2023.log)

**Comment by cagnulein** [comment]
argh ok, i'm restoring the patch that i did that it was showing bt connected. it's building, let's see if it will change the effect. sorry for all these test but without the elliptical i can't test on my own :(

**Comment by Intellirump** [comment]
No trouble at all, no need to apologize, I'm as patient and willing as you
are and no pressure at all from my end ☺️ welcome to keep trying as long as
U feel like it, I appreciate the effort whether it works or doesn't work in
the end.

**Comment by cagnulein** [comment]
thanks! ok done https://github.com/cagnulein/qdomyos-zwift/suites/18968574288/artifacts/1108859820
same test as before. if i'm right now you should see the "bt connected"thing. what i'm hoping is that also the metrics will pop up!

**Comment by Intellirump** [comment]
[debug-Tue_Dec_12_21_35_40_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13647607/debug-Tue_Dec_12_21_35_40_2023.log)

No luck on this one 🙈

**Comment by cagnulein** [comment]
don't you see the bt connected?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 dic 2023 alle ore 12:40 Intellirump <
***@***.***> ha scritto:

**Comment by Intellirump** [comment]
Strangely no, it doesn't say it on the machine. Just the same msg displays
on the QZ app that says the name of the machine and that it's 'found' but
no metrics.

**Comment by cagnulein** [comment]
mmm ok that's an important thing so, ok i'm building another one

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/suites/18971694306/artifacts/1109103932
same test
thanks!

**Comment by Intellirump** [comment]
[debug-Wed_Dec_13_17_43_51_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13657728/debug-Wed_Dec_13_17_43_51_2023.log)
Thanks, the BT Connected is now showing again! However, no metrics. Ensured iconsole eliptical on and virtual Bluetooth device setting was disabled. Sorry for the headache!

**Comment by cagnulein** [comment]
> My machine won't allow me to press start, everything is disabled on it when it connects to a compatible app and the app takes control. There is no option to over ride this that I can see, no buttons to press. It certainly is strange. It seems like it's strictly pre wired to only connect with these certain apps like Kinomap and Fitlink which it was advertised with...I can't pair it with my phone or tablet alone, needs an app.
> 
> I have attached a Kinomap snoop log . [btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13458193/btsnoop_hci.log)
> 
> 🙂

ok I have a question: when you collected this log from kinomap, the elliptical was just started? or did you use it before without unplugging it? Since I'm sending now the same kinomap frame over bluetooth, I'm wondering if maybe the elliptical on kinomap, was on a different state. So what I suggest is, if you didn't do this:
1. turn off your elliptical
2. turn off kinomap
3. turn on your elliptical
4. do a simple session on kinomap recording the hci snoof

In this way both QZ and Kinomap should be in the same state. Does it sound right to you?
