### ISSUE TITLE
[BUG] Proform 225CSX resistance does not work

### ISSUE THREAD

**Issue by faceofpen** [cagnulein/qdomyos-zwift#1903]
**Describe the bug**
Auto resistance, target resistance, and adjusting resistance via the app does not work. 

**To Reproduce**
1. Set target resistance / initial resistance to a value

**Expected behavior**
Resistances should respond correctly to target & auto resistance. Pressing the + button in the app should increase the resistance.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 14

Debug log attached. I have cycled from level 1 resistance (initial) to the highest setting (20). 
[debug-Fri_Dec_22_17_25_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13749045/debug-Fri_Dec_22_17_25_05_2023.log)

**Comment by cagnulein** [comment]
hi! did you already try all the nordictrack proform setting in the proform
bike settings? one by one, leaving only one enabled at a time and
restarting the app after each change?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 dic 2023 alle 07:35 faceofpen ***@***.***>
ha scritto:

**Comment by faceofpen** [comment]
Hey, thanks for your quick reply

I tried the proform bike settings just now as you described. The closest option was the NordicTrack GX 2.7, which looks to be similar to the 225CSX. The resistance settings were more accurate though still had 2 missing levels.

I could not adjust the resistance in-app by pressing the - and + buttons on resistance, and increasing target resistance did not change the resistance on the bike either.

Cheers

**Comment by cagnulein** [comment]
hi so this means that you have to collect a hci log following this guide
with the ifit app changing the resistance from the ifit app directly
let me know

https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 dic 2023 alle 05:08 faceofpen ***@***.***>
ha scritto:

**Comment by faceofpen** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13760427/btsnoop_hci.log)
Hey mate

All done - I used the iFit app to increase resistance from 1-10. Here's the attached log.

Cheers, merry christmas

**Comment by cagnulein** [comment]
thanks! i will check this after Christmas! Merry Christmas to you too!

**Comment by cagnulein** [comment]
@faceofpen done! https://github.com/cagnulein/qdomyos-zwift/actions/runs/7321554115 download from the bottom of this page

I added a new setting in the proform bike section for your bike.

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link. In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to [roberto.viola83@gmail.com](mailto:roberto.viola83@gmail.com) mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by faceofpen** [comment]
thanks mate! I enabled the new setting and tried it on Zwift for a few minutes and noticed that:

- the bike's resistance was changed automatically (great!)
- speed, cadence, and watts stopped updating with the setting enabled. when i turned the setting off & restarted the app, these stats were updating again

sorry about this! thanks

**Comment by cagnulein** [comment]
ok great, i will check this, sounds like a stupid issue :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 dic 2023 alle 06:35 faceofpen ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@faceofpen i guess i fixed! https://github.com/cagnulein/qdomyos-zwift/actions/runs/7327701458
Let me know

**Comment by faceofpen** [comment]
Hey

Gave it a go with that new version today and it looks like it's still happening - speed, cadence, and watts will update once and then won't update again. Looks like the same thing is happening to the resistance and target resistance this time.
I attached two debug logs. Dec_26_28_08_20_35_2023 is the second log that I made, where I was increasing the resistance from 1-20. Dec_28_08_13_22_2023 is the first log where I just ran the bike for a few minutes.

[debug-Thu_Dec_28_08_20_35_2023[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13781670/debug-Thu_Dec_28_08_20_35_2023.1.log)
[debug-Thu_Dec_28_08_13_22_2023[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13781600/debug-Thu_Dec_28_08_13_22_2023.1.log)

Thanks for your help mate

**Comment by cagnulein** [comment]
ok i guess i did it now https://github.com/cagnulein/qdomyos-zwift/actions/runs/7345616787

**Comment by faceofpen** [comment]
Working perfectly now. Thanks so much mate.

**Comment by cagnulein** [comment]
amazing!
