### ISSUE TITLE
[BUG] Pofiles screen not showing profiles on Raspberry PI OS

### ISSUE THREAD

**Issue by josetta** [cagnulein/qdomyos-zwift#1976]
**Describe the bug**
Hi, I am using app on RPI4, I am setting 2 profiles, one for me (I am using elliptical for run) and one for wife (she is using it as bike), but I can't see those profiles in Profiles part... on android, it is showing but on RPI4 it is not. I can see profile files exists in other folders, adding screenshots

**To Reproduce**
1. Go to Menu -> Profile
2. Fill profile name and save
3. Repeat point 1 and 2 with another name
4. Go to Menu ->Profile
5. Click on Profiles
6. You will see no profiles

**Expected behavior**
I should see saved profiles in Menu ->Profile screen

**Screenshots**
![obrázok](https://github.com/cagnulein/qdomyos-zwift/assets/40663601/0b5e1ac1-6562-4b2e-ad9b-08f55e147422)
![obrázok](https://github.com/cagnulein/qdomyos-zwift/assets/40663601/c3c0b879-ab4d-439c-bbf6-cf004fa1a75a)

**Desktop (please complete the following information):**
 - OS: Raspberry PI OS with Desktop
 - Version: Kernel 6.1, Debian version 12

**Append a debug log**

**Additional context**

**Comment by cagnulein** [comment]
it shows something in the debug log about this? the code should point to the right folder

**Comment by josetta** [comment]
I didn't notice anything in logs in console but I can add log :)

**Comment by josetta** [comment]
added log after running, going to profiles and saving profile... there is some warning about using Layout and some undefined behavior, maybe it is connected to it?

[debug-ut_jan_9_13_15_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13873650/debug-ut_jan_9_13_15_27_2024.log)

**Comment by cagnulein** [comment]
I guess this is the error

qrc:/profiles.qml  qrc:/profiles.qml:12: TypeError: Cannot read property
'top' of null

I don't know why it's happening only on the raspberry Pi, maybe a Qt issue
on ARM.
Also the training program and gpx list do the same?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 gen 2024 alle ore 13:24 josetta ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
give a try to this branch Pofiles-screen-not-showing-profiles-on-Raspberry-PI-OS-#1976

**Comment by josetta** [comment]
THX, I will try, about GPX and training program, yes, it looks weird and there is missing data that are in android

**Comment by cagnulein** [comment]
so also the training program and gpx are missing? are the folder of gpx and training program not empty?

**Comment by josetta** [comment]
ah my mistake, TP a GPX shows folders and after I selected correct folder, it shows correctly... I will test branch right after lunch :)

**Comment by cagnulein** [comment]
Sounds good!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 gen 2024 alle ore 13:48 josetta ***@***.***>
ha scritto:

**Comment by josetta** [comment]
profiles still do the same, they are not showing, after switching and pulling branch, i build it by manual for linux https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/10_Installation.md so I hope, I did it right :D latest log:
[debug-ut_jan_9_15_19_25_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/13875085/debug-ut_jan_9_15_19_25_2024.zip)

**Comment by cagnulein** [comment]
ok the error disappear, the UI changed or it was completely the same?

**Comment by josetta** [comment]
UI is the same, I can't see profiles. I clicked few times on it in this new log.
![obrázok](https://github.com/cagnulein/qdomyos-zwift/assets/40663601/162bd160-e4e4-4e0d-af8b-27aafc5112a6)
![obrázok](https://github.com/cagnulein/qdomyos-zwift/assets/40663601/caa18d0a-796c-45e0-8e79-23ebfd4338d0)
[debug-ut_jan_9_16_11_47_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/13875544/debug-ut_jan_9_16_11_47_2024.zip)

**Comment by cagnulein** [comment]
ok i'm going to build it on my test rig, let's see if i can see the same
issue
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 gen 2024 alle ore 16:18 josetta ***@***.***>
ha scritto:

**Comment by josetta** [comment]
Hi and have a nice day, any news on this? :)

**Comment by cagnulein** [comment]
No, not yet, I have currently the flu and I'm overwhelmed by tasks. I
didn't forget about this.
Thanks


Il giorno mar 30 gen 2024 alle 06:28 josetta ***@***.***> ha
scritto:

**Comment by josetta** [comment]
ou, I am sorry, so get well soon :) I just wrote something so bot won't close it :)

**Comment by cagnulein** [comment]
>

**Comment by josetta** [comment]
Hi :D I trained after long time on machine, any news on this? :) THX

**Comment by cagnulein** [comment]
Yes I guess I already fixed for qt6. Raspberry will be soon to qt6 for qz!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 mag 2025 alle 19:39 josetta ***@***.***> ha
scritto:

**Comment by josetta** [comment]
hi, I again trained with actual version from master, but I can't still see profiles, any news? :)

**Comment by cagnulein** [comment]
hi @josetta as i said i'm porting the code to qt6. windows is al;ready working, android is the next. then ios and finally linux. i'm overwhelmed by work so i'm trying to do my best

**Comment by josetta** [comment]
OK :) just to be sure, when it will be there, it will be in master branch right? :)

**Comment by cagnulein** [comment]
yes, for sure it will be first available in the q6 branch. then when all
the architecture will be ported to qt6 will be on the master

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 set 2025 alle ore 10:53 josetta ***@***.***>
ha scritto:
