### ISSUE TITLE
[REQ] Incline control device support request Sole TT8

### ISSUE THREAD

**Issue by tlupfer** [cagnulein/qdomyos-zwift#2249]
Currently QZ detects my Sole TT8 (2023, latest software 1.3) and reports the speed and incline correctly, but is not able to control either. When "Inclination (experimental)" is enabled, it no longer detects either metric and still cannot control them. I would like to be able to control the incline (and speed, but I don't think that will be possible since I also cannot control that from the Sole+ app) from QZ.

From the Sole+ app I am able to start and stop the treadmill, and control the incline. I have attached a bluetooth log of the following: starting the treadmill, going from 0 to 15 degrees in 1 degree increments via the Sole+ app, then from 15 degrees to -6 degrees in one degree increments, and finally from -6 to 0 degrees in one degree increments, finishing the activity. There are likely two iterations of this process in the log.

Thanks for your hard work on this project!

[sole_tt8_btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14729977/sole_tt8_btsnoop_hci.log)

**Comment by cagnulein** [comment]
@tlupfer done!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8417071805

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by tlupfer** [comment]
I was able to test this from the build artifact in your link (I hadn't previously installed QZ on this android device as I normally use an iPhone) and found that some things are now working (hurray!) while a few others still aren't.

Working:

- Starting and stopping the treadmill
- Decreasing the inclination between 15 degrees and 0 degrees

Not working:

- Increasing the incline (does not work in any range)
- Decreasing the incline below zero degrees (this model goes to -6 degrees in 1 degree increments, but QZ stops responding at 0 degrees)

Let me know if any additional logging would be useful. Thanks!

**Comment by cagnulein** [comment]
Great! Please share a debug log showing the issues

https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 mar 2024 alle 18:52 Tim Lupfer ***@***.***>
ha scritto:

**Comment by tlupfer** [comment]
Log file below. What I did:

- Start treadmill with QZ
- Manually set the treadmill at 15 degrees with the physical button
- Used QZ to move the treadmill back to 0 degrees
- Attempt to increase the incline with QZ (no response)
- Attempt to decrese the incline below 0 degree with QZ (no response)
- Stop treadmill with QZ

[debug-Thu_Mar_28_12_46_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14793738/debug-Thu_Mar_28_12_46_10_2024.log)

**Comment by cagnulein** [comment]
Thanks! i will check after easter days

**Comment by cagnulein** [comment]
@tlupfer maybe i fixed it! Does your treadmill has 0.5 grade or 1%? if it's only 1% set 1 instead of 0.5 into the min step inclination setting in the treadmill section in qz! Let me know!

**Comment by tlupfer** [comment]
> @tlupfer maybe i fixed it! Does your treadmill has 0.5 grade or 1%? if it's only 1% set 1 instead of 0.5 into the min step inclination setting in the treadmill section in qz! Let me know!

As, yes, this does fix the ability to increase the incline. I am still not able to get below 0% when decreasing the incline, but that is the last remaining issue I'm having. Thanks!

**Comment by cagnulein** [comment]
Great! Ok let me check this too, it's a simple one

**Comment by cagnulein** [comment]
@tlupfer any news?
