### ISSUE TITLE
Pro-Form 595i ProShox2

### ISSUE THREAD

**Issue by Msieurseb62** [cagnulein/qdomyos-zwift#2287]
Hello, I do not have auto elevation on my treadmill via Zwift.

Zwift runs on my iPad and QZ runs my Pixel 7 Android.

Thx

[debug-Wed_Apr_10_10_01_22_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14929476/debug-Wed_Apr_10_10_01_22_2024.log)

**Comment by cagnulein** [comment]
hi @Msieurseb62 in this log i can't see any connection with your treadmill. in order to understand your issue i need to see a connection with the treadmill

Let me know

**Comment by Msieurseb62** [comment]
[debug-Mon_Apr_22_15_29_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15064839/debug-Mon_Apr_22_15_29_30_2024.log)

**Comment by cagnulein** [comment]
Hi, first of all are you able to change the inclination or the speed from the speed and inclination tile manually from qz? which nordictrack model is this?

**Comment by Msieurseb62** [comment]
Treadmill Pro-Form ProShox2 - and no I cannot control my treadmill via QZ.

**Comment by cagnulein** [comment]
that's the issue. in order to add auto speed and auto inclination follow this with the ifit app https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Let me know

**Comment by cagnulein** [comment]
@Msieurseb62 i guess i already added your treadmill. You have to enable it in the nordictrack settings, under the treadmill settings in QZ and select the proshox2
Let me know!

**Comment by Msieurseb62** [comment]
Hello, I hadn't actually done the tutorial: https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

On the other hand, yes in the QZ options, there is my treadmill.  I selected ProForm ProShox2 but I still cannot control my treadmill via QZ.

**Comment by cagnulein** [comment]
In your last log it wasn't, are you sure? Anyway let's follow the tutorial
so I can implement it in case

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 apr 2024 alle 16:06 Msieurseb62 ***@***.***>
ha scritto:

**Comment by Msieurseb62** [comment]
No, I didn't do it last time, but I did it today and it's still the same.

![Screenshot_20240424-160722](https://github.com/cagnulein/qdomyos-zwift/assets/166596112/6f221422-7f2e-4934-b947-521e1f1ee81b)

**Comment by Msieurseb62** [comment]
Build info: panther-user 14 AP1A.240405.002 11480754 release-keys
Serial number: 34211FDH2004ZM 

[bugreport-panther-AP1A.240405.002-2024-04-24-16-21-59.zip](https://github.com/cagnulein/qdomyos-zwift/files/15095825/bugreport-panther-AP1A.240405.002-2024-04-24-16-21-59.zip)

I hope I didn't do anything stupid.

**Comment by cagnulein** [comment]
got it, it's indeed a different version from the one that I implemented here #2078 
@daveadavidson which version of this do you have? and you @Msieurseb62  ? i mean the long model number so i can add it in the settings to detail it.
I will add this in the next days

**Comment by Msieurseb62** [comment]
Pro-Form 595i ProShox2 - Treadmill
Model N° PETL78717.1 220-240v 50/60hz 1500w

**Comment by Msieurseb62** [comment]
Perfect 👍

**Comment by cagnulein** [comment]
I didn't forget about you, I'm having horrible days at work unfortunately :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 apr 2024 alle ore 19:17 Msieurseb62 <
***@***.***> ha scritto:

**Comment by daveadavidson** [comment]
Hi mate,
Not a problem I hope everything works out and gets better. My issue isn't
important so no rush needed
Dave

**Comment by Msieurseb62** [comment]
Take your time ;)

**Comment by cagnulein** [comment]
adding the extracted part from the log, i'm building the new version
[595i.json](https://github.com/cagnulein/qdomyos-zwift/files/15185496/595i.json)

**Comment by cagnulein** [comment]
@daveadavidson @Msieurseb62  done

https://github.com/cagnulein/qdomyos-zwift/actions/runs/8921000025

be sure to select the new proform 595i proshox2 device in the nordictrack/proform treadmill combobox and restart qz

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Msieurseb62** [comment]
Hello, 

I'm going to wait for QZ beta to update on Play Store because I don't know how else to do it.

Thx

**Comment by daveadavidson** [comment]
Same here lol I'm such a n00b lol

**Comment by cagnulein** [comment]
uninstall qz
download this one and install it https://github.com/cagnulein/qdomyos-zwift/actions/runs/8921000025/artifacts/1466438254

select the new proform device as i said
restart qz
try :)

**Comment by Msieurseb62** [comment]
Hello, I cannot change the speed via QZ and auto elevation does not work.  I entered my Zwift credentials and chose my Pro-Form 595i mat from the list and relaunched the App.

**Comment by cagnulein** [comment]
@Msieurseb62 first of all try the plus button on the speed tile and inclination tile. neither of them work? create a debug log so i can check if the implementation is matching the hci snoof

**Comment by Msieurseb62** [comment]
On the other hand, I installed APK but the .json file, what should I do with it?

**Comment by cagnulein** [comment]
> On the other hand, I installed APK but the .json file, what should I do with it?

nothing, it's just a github file. ignore it

**Comment by Msieurseb62** [comment]
[debug-Tue_May_7_11_53_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15233785/debug-Tue_May_7_11_53_44_2024.log)

**Comment by Msieurseb62** [comment]
No button works on QZ whether it is speed or incline.

**Comment by cagnulein** [comment]
got the error. already fixed here https://github.com/cagnulein/qdomyos-zwift/actions/runs/8983442459
you will see the new apk there in the bottom of the page in 30 minutes

**Comment by Msieurseb62** [comment]
I downloaded apk 2.16.53 and still have the same problems.  Sorry.

**Comment by cagnulein** [comment]
attach a debug log from this one and i will check it. maybe it's not the
same issue. did you set again the new setting?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 7 mag 2024 alle 12:55 Msieurseb62 ***@***.***>
ha scritto:

**Comment by Msieurseb62** [comment]
Hello, 

Sorry I have some small personal problems, I will send you the file tomorrow.

Thx

**Comment by cagnulein** [comment]
No problem, thank you for the update.


Il giorno gio 23 mag 2024 alle 12:40 Msieurseb62 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Msieurseb62 any news?
