### ISSUE TITLE
[BUG] 3G Cardio Elite Recumbent Bike X  - Resistance not working

### ISSUE THREAD

**Issue by acepilot111** [cagnulein/qdomyos-zwift#2488]
**Describe the bug**
New recumbent bike, 3G Cardio Elite RB X
https://www.3gcardio.com/shop/elite-rb-x-recumbent-bike/

Manual:
https://www.3gcardio.com/downloads/3G-Elite-RB-X-Recumbent-Bike-Manual.pdf

QZ app connects to the bike when app is open and bike is powered on. Some info seems odd like the kCal showing 120+ per minute. But, most importantly, I cant control the resistance with either the app or the local controls on the bike itself. When it connects it defaults to level 1 resistance. (Max is 16) Then as I start to pedal the resistance changes on its own depending on how hard I pedal. If i take it easy, it goes to around 8. If I start pushing it goes to max at 16. The controls in the app dont seems to be doing anything. 

**To Reproduce**
Connect the bike to Bluetooth and start peddling. 

**Expected behavior**
I would like to be able to control the resistance with either the bike or the app. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Android
 - Version 2.16.66 (I think I found a link to join the beta already.)

**Smartphone (please complete the following information):**
 - Device: Galaxy s23 Ultra (SM-S918U1)
 - OS: Android
 - Version 14

**Append a debug log**
[debug-Sun_Jul_28_16_41_58_2024.log](https://github.com/user-attachments/files/16405346/debug-Sun_Jul_28_16_41_58_2024.log)

  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks i will check it later today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 lug 2024 alle 00:03 acepilot111 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
#2173

**Comment by cagnulein** [comment]
hi @acepilot111 i fixed the kcal. About the resistance: I guess I understood your issue. Let's try this in order to understand:
- go to qz settings and go to the accessories, smart spin 2k and enable the "Peloton Bike" setting
- restart qz
- try to change resistance, is any better? in case send me another log

Thanks

**Comment by acepilot111** [comment]
That did make a difference in that I can now control the resistance from the manual controls on the bike itself. Still unable to control them from that app. Attached is a log of cycling through each resistance setting on the bike.

Nathan
________________________________

**Comment by cagnulein** [comment]
hi you have to attach the debug log directly in the github interface otherwise I can't see it. Thanks

**Comment by acepilot111** [comment]
[debug-Mon_Jul_29_05_48_33_2024.log](https://github.com/user-attachments/files/16413908/debug-Mon_Jul_29_05_48_33_2024.log)

**Comment by cagnulein** [comment]
ok the bike doesn't accept the resistance also in this way.
so the only way it's changing according the inclination as i was doing before. so disable the "Peloton Bike" setting and try to set the zwift resistance offset to 0 instead of 4 in the bike setting and try to change the resistance. it should be a little better. we have only to understand the "ratio" that the bike wants to control one resistance level at a time
Let me know

**Comment by acepilot111** [comment]
Got it. Made the change but wont be able to test until I get home tonight. Will let you know the results when I can.

**Comment by acepilot111** [comment]
Alright, I tried changing that setting from 0 through 20 and none of them made the bike change its resistance. 
[Uploading debug-Mon_Jul_29_19_03_14_2024.log…]()

**Comment by cagnulein** [comment]
hi the log is corrupted, you have to wait to finish the upload before submitting. thanks

**Comment by cagnulein** [comment]
i guess I found your issue you have to ride to change the resistance: in fact in the first log i saw the resistance changing and the difference is that you were riding.

Let me know

**Comment by acepilot111** [comment]
I just tested that and riding or not, was unable to change the resistance with the app. 

In this first log I was able to change the resistance with the bike controls with and without peddling, but not with the app in either case. In this log I had the peloton bike setting turned on in accessories>smartspin2k so that the bike controls would still work. 


[debug-Wed_Jul_31_05_48_37_2024.log](https://github.com/user-attachments/files/16440247/debug-Wed_Jul_31_05_48_37_2024.log)

In this log I turned the peloton bike setting off in accessories>smartspin2k and was again unable to control the resistance with either the bike controls or the app when I was peddling or still. 

[debug-Wed_Jul_31_05_54_40_2024.log](https://github.com/user-attachments/files/16440282/debug-Wed_Jul_31_05_54_40_2024.log)

**Comment by cagnulein** [comment]
hah ok so in either case QZ controls the bike resistance. So I'm guessing if it's possible at all to control it by bluetooth. Do you have any app that controls it over bluetooth?

**Comment by acepilot111** [comment]
I finally got a chance to try it yesterday using Kinomap and it seemed to be able to control the resistance over wifi. I wasnt able to control it manually like in QZ (I couldn't find any way to manually adjust resistance. The app only seems to adjust resistance based on the slop of the track your virtually ridding.), but when I got the virtual hill, the resistance on the bike increased. That seems indicative that the app was able to send some kind of signal to modify the existing resistance. 

Also, I noticed a few days ago while doing some more testing using UZ on my phone that there was one way I could control the resistance on the bike using QZ. If I disable the Peloton bike option under smartspin2k and start peddling to increase the resistance, if tap the resistance decrease button in the app, the resistance goes all the way down to 1 instantly. Also, when I have the peloton option enable and change the resistance manually on the bike itself, if I tap the resistance increase button the bike does the same thing, the resistance goes all the way back to one. Here is a log of that happening. 

[debug-Sun_Aug_4_07_59_08_2024.log](https://github.com/user-attachments/files/16487630/debug-Sun_Aug_4_07_59_08_2024.log)

**Comment by cagnulein** [comment]
thanks @acepilot111 
I tried a new approach https://github.com/cagnulein/qdomyos-zwift/actions/runs/10244121462

I tried a new approach.

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
so sorry to hear this, i guess i found the solution for this :(
which bike will you buy now?

**Comment by acepilot111** [comment]
Not sure yet. Will have to start searching again. I got this one because it has an adjustable back rest, but that also made it rather pricey. Not sure I want to spend that much again.
