### ISSUE TITLE
[BUG] bluetooth connection issue of keep bike

### ISSUE THREAD

**Issue by DavidXch** [cagnulein/qdomyos-zwift#2543]
I use QZ on my ipad with IOS12 to connect my keep C1 mini. I can find the bluetooth of the bike in the device list, but the bluetooth can not be successfully connetted. I have tried all the methods mentioned in the guidance while they didn't work.

My ipad is ipad mini2 with IOS12 and my bike is keep C1 mini, thus i think maybe its connection is different to keep C1?(i see that C1 is in the supported devices)

then how can i fix this problem, thanks

**Comment by cagnulein** [comment]
hi can you install the free app nrfconnect and show me a screenshot about
your fitness device?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 ago 2024 alle 18:28 DavidXch ***@***.***> ha
scritto:

**Comment by DavidXch** [comment]
thanks for response, i find nrfconnect in appstore but i can't install the 'nRF Connect for Mobile' since it only supports IOS16+, so i just install 'nRF Connect Device Manager' instead.
it is excited to find my device in the app but all the things are just 'unknown', what should i do :)
![img1](https://github.com/user-attachments/assets/8717adf3-29a2-4dc4-90e2-6abd050e9155)

**Comment by DavidXch** [comment]
i also find that the status is first 'connecting' and then becomes 'disconnected', hope this is helpful to solve the problem

**Comment by DavidXch** [comment]
sorry since i'm not familier to this, i now download this app on my mobile phone and connect to the bike, the information is as following, is this the information you needed
![img2](https://github.com/user-attachments/assets/7943741f-3b2c-416d-b0fe-5b5db6a2210d)
![img3](https://github.com/user-attachments/assets/eeda22cc-b474-433a-b737-aea73f190dc0)

**Comment by cagnulein** [comment]
Yes it's ok but I need the full page of them. Can you scroll down and make other screenshots?
Thanks

**Comment by DavidXch** [comment]
sure, here is the rest of the page, hope helpful:
![img4](https://github.com/user-attachments/assets/2de86689-22aa-480f-8c1d-dc941ded5be2)

**Comment by cagnulein** [comment]
This is perfect, thank you!
I will try to add it today!

Il giorno mer 28 ago 2024 alle 07:31 DavidXch ***@***.***> ha
scritto:

**Comment by DavidXch** [comment]
ok, really thank you sir :)
and a small question: is 'add' means that my bike is different to the supported 'keep C1' thus QZ doesn't work?

**Comment by cagnulein** [comment]
yes exactly :)

**Comment by cagnulein** [comment]
done! https://github.com/cagnulein/qdomyos-zwift/actions/runs/10591000852

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
here https://github.com/cagnulein/qdomyos-zwift/actions/runs/10591000852/artifacts/1863300218

**Comment by DavidXch** [comment]
ok, i get it

**Comment by DavidXch** [comment]
good news that QZ is able to connect to my bike now, but all the data is 0 and the start button is shining, is this because the apk is a trial version?
![img5](https://github.com/user-attachments/assets/ab6da5c3-f956-4682-b723-60d726347092)

**Comment by cagnulein** [comment]
nope it means there is something else, please add here a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by DavidXch** [comment]
ok, i find the log file here
[debug-Wed_Aug_28_15_42_32_2024.log](https://github.com/user-attachments/files/16778363/debug-Wed_Aug_28_15_42_32_2024.log)

**Comment by cagnulein** [comment]
hi @DavidXch can you please upload it again? i can download it

**Comment by DavidXch** [comment]
sure, hope it is helpful
[debug-Wed_Aug_28_15_42_32_2024.log](https://github.com/user-attachments/files/16779007/debug-Wed_Aug_28_15_42_32_2024.log)

**Comment by cagnulein** [comment]
@DavidXch ok so the bike is indeed very different from the one that I implemented. I tried a patch here https://github.com/cagnulein/qdomyos-zwift/actions/runs/10593777318

You will see the apk at the bottom of the page

Let me know!

**Comment by DavidXch** [comment]
ok, i will try this new version soon :)

**Comment by DavidXch** [comment]
hi, i have tried the latest version but the same problem still exists, here is the new log file:
[debug-Wed_Aug_28_17_58_40_2024(1).log](https://github.com/user-attachments/files/16781712/debug-Wed_Aug_28_17_58_40_2024.1.log)

**Comment by cagnulein** [comment]
ok we have to find an app that handles this protocol. Did you test the kinomap app? if it works I can mimic the same behavior from it.
Let me know

**Comment by DavidXch** [comment]
fine, it seems that keep claims that their devices can only use with their own app, while i will try kinomap now and see if it works

**Comment by DavidXch** [comment]
ok, i will follow this guide to collect information from the keep app

**Comment by DavidXch** [comment]
here is the log file, however i can't find bt directory, if this because i use Harmony OS?, so i just update the whole bugreport, hope it is helpful
to use this bike in keep, i first need to scan the QR code on the device to bind it to the account, and at every time to use it, i just need to select the device and start.
[bugreport-ABR-AL60-HUAWEIABR-AL60-2024-08-28-18-4.zip](https://github.com/user-attachments/files/16782295/bugreport-ABR-AL60-HUAWEIABR-AL60-2024-08-28-18-4.zip)

**Comment by cagnulein** [comment]
Unfortunately I need the Bluetooth log, did you enable the hci setting in
the developer settings?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 28 ago 2024 alle 12:53 DavidXch ***@***.***> ha
scritto:

**Comment by DavidXch** [comment]
yes, i just follow the guide and open the HCI log collection, maybe i should do it again

**Comment by cagnulein** [comment]
Yes, please!
Maybe try to revert the order, some android phone behaves differently

Il giorno mer 28 ago 2024 alle 13:00 DavidXch ***@***.***> ha
scritto:

**Comment by DavidXch** [comment]
ok, it seems that the bug report of harmonyOS doesn't conclude the HCI information, so i just use adb to pull them out, here is the log files(totally three tries thus three logs and i don't know which is the right one)
[bt.zip](https://github.com/user-attachments/files/16782636/bt.zip)

**Comment by cagnulein** [comment]
that's great! i'm checking! for future reference, could you please describe
where did you pull them from?
It could be useful for other users
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 28 ago 2024 alle ore 13:31 DavidXch ***@***.***>
ha scritto:

**Comment by DavidXch** [comment]
ok, i just link the phone to PC and use order 'adb pull /data/log/bt', this method is found in harmony community https://developer.huawei.com/consumer/cn/forum/topic/0203853078674020018

**Comment by cagnulein** [comment]
argh unfortunately all the 3 logs are showing these

<img width="976" alt="Screenshot 2024-08-28 at 13 35 30" src="https://github.com/user-attachments/assets/4ad17ec0-3e43-46e5-856c-e8b8e57b1989">

do you have any other android too? it could be an issue of harmonyos unfortunately :(

**Comment by DavidXch** [comment]
i need some time to find another andriod device, i will try to do it again on other devices

**Comment by DavidXch** [comment]
i find that wirelessshark seems to be able to open the log normally
here i put a screenshot of it, since i haven't analyse the bluetooth communication so if the log is opened correctly? since it is not easy for me to find another andriod device
![image](https://github.com/user-attachments/assets/5cd10d0a-c34b-4545-ae19-b9d4a808989d)

**Comment by cagnulein** [comment]
yes but the frames from your phone to the keep device haven't any bytes, you can scroll down to see them

**Comment by DavidXch** [comment]
yes i find it, so i will try it on an andriod device

**Comment by DavidXch** [comment]
i try to catch HCI on an andriod device, but i still can't find the bt file, but i have find a bluetooth log file, while it is not a log type but curf, if this is the one you needed?(the only andriod device i can find is very old and it is andriod 8)
[BT_HCI_2024_0828_211102.cfa.zip](https://github.com/user-attachments/files/16784173/BT_HCI_2024_0828_211102.cfa.zip)

**Comment by DavidXch** [comment]
it seems that this log has the same problem as that cathced on harmony OS

**Comment by cagnulein** [comment]
yes this one works! wow this protocol is such a nightmare! this is from the official app? can you try also with the kinomap app here?

**Comment by cagnulein** [comment]
nope the log is fine!

**Comment by DavidXch** [comment]
yes, i tried kinomap, but i can't find keep in it, if this app support other bands?

**Comment by cagnulein** [comment]
> yes, i tried kinomap, but i can't find keep in it, if this app support other bands?

do you mean qz or kinomap?
anyway i will try implement it with the log above, i guess I will need a little of time because the protocol is very hard

**Comment by DavidXch** [comment]
maybe i can try it again to connect it by kinomap

**Comment by DavidXch** [comment]
sure, i will also try to use kinomap and tell you the result in time, thanks a lot

**Comment by DavidXch** [comment]
> > yes, i tried kinomap, but i can't find keep in it, if this app support other bands?
> 
> do you mean qz or kinomap? anyway i will try implement it with the log above, i guess I will need a little of time because the protocol is very hard

i mean kinomap since the app let me to select a band and a type of fitness device, while i can't find keep there

**Comment by cagnulein** [comment]
hah ok so neither kinomap support it. i guess we have to stick with their official app and the log that you created. i hope it will be enough!

**Comment by DavidXch** [comment]
yeah, it is obvious that keep doesn't hope their users use the bike with other softwares lol, hope everything goes well! :)

**Comment by cagnulein** [comment]
do you have the apk of this keep app? i would like to decompile it because otherwise it could quite challenging to implement

**Comment by DavidXch** [comment]
ok, here it is, but it is too large, maybe you can download it from apkpure?

**Comment by cagnulein** [comment]
sure, can you share the link?

**Comment by DavidXch** [comment]
and here is also a quick link: https://dl-android.keepcdn.com/release/apk/keep_keep_homepage___default_8.2.50_a4408c7f.apk

**Comment by cagnulein** [comment]
Thanks, I'll check it out.
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 28 ago 2024 alle ore 16:32 DavidXch ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
mmm... they crypted it. is it a brand new bike?

**Comment by DavidXch** [comment]
well its actually not new, i bought it near two years ago.
besides, i found an apk that can connect this app to zwift directly but this is just a tried version (i try to connect the author but failed) so all the outputs like power are 100, and i tried to analyze it but failed since i don't know andriod development well, so this may help, the package is too large so maybe i can send it to you through email?

**Comment by cagnulein** [comment]
sure send me to roberto.viola83 at gmail.com

**Comment by DavidXch** [comment]
ok, i have sent the mail

**Comment by DavidXch** [comment]
oh no, my email is broken, i'll try to send it again through another one

**Comment by cagnulein** [comment]
unfortunately even with jadx app the code is obfusced. we should need to find another simple app that can collect the info from it. the apk that you just sent me it's the official from Keep, just trial?

**Comment by DavidXch** [comment]
well, the first apk is the official version and the last one is a modded version by another author while i can't connect with him

**Comment by cagnulein** [comment]
it would be useful to have a contact with him, maybe it has decompiled it correctly! is he from your country?

**Comment by cagnulein** [comment]
you can invite him here if you can!

**Comment by cagnulein** [comment]
@DavidXch Any news?

**Comment by DavidXch** [comment]
Unfortunately,i haven't received any replies from the original author. I will keep containing.



---Original---
From: "Roberto ***@***.***&gt;
Date: Sat, Sep 21, 2024 16:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cagnulein/qdomyos-zwift] [BUG] bluetooth connection issue ofkeep bike (Issue #2543)




 
@DavidXch Any news?

**Comment by cagnulein** [comment]
Ok, thanks for the update.


Il giorno sab 21 set 2024 alle 10:58 DavidXch ***@***.***> ha
scritto:
