### ISSUE TITLE
[BUG] Zwift Click connection issue

### ISSUE THREAD

**Issue by camster007** [cagnulein/qdomyos-zwift#2576]
[debug-Fri_Sep_6_13_14_00_2024.log](https://github.com/user-attachments/files/16907033/debug-Fri_Sep_6_13_14_00_2024.log)
Zwift click doesn't connect 

**To Reproduce**
1. Open QZ followed by Zwift
2. Click on controls _> search
3. No response

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11 
 -  - Version 10.0.22631 Build 22631

**Smartphone (please complete the following information):**
 - Device: Pixel 7 pro
 - OS: Android
 - Version 14,

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Got the issue, I fixed it yesterday download this https://github.com/cagnulein/qdomyos-zwift/actions/runs/10736435916/artifacts/1900643801

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
It was about this one https://github.com/cagnulein/qdomyos-zwift/commit/1ade0788275e1ae50215998e36000502d73090ec
#2531

**Comment by camster007** [comment]
I downloaded the apk , but  unfortunately the problem remains. Could it be the updated version of Zwift that causes the issue?

**Comment by cagnulein** [comment]
no zwift it's not involved, could you please show me a fresh debug log?
also are you following these steps:
1) close qz and zwift
2) wake up zwift play and the trainer
3) open qz
4) zwift play should be connected in 4-5 seconds
5) open zwift then

**Comment by camster007** [comment]
I don't have the play combination, just the click. I don't suppose that makes a difference. 

I can see the click under the advanced settings -> manual device option.

**Comment by cagnulein** [comment]
ok so 
no zwift it's not involved, could you please show me a fresh debug log?

close qz and zwift
wake up zwift click and the trainer
open qz
zwift click should be connected in 4-5 seconds
open zwift then

**Comment by camster007** [comment]
[debug-Fri_Sep_6_16_50_41_2024.log](https://github.com/user-attachments/files/16909682/debug-Fri_Sep_6_16_50_41_2024.log)

**Comment by cagnulein** [comment]
ok i can see it! it's all fine, ignore the popup, i have to fix it for the click!

**Comment by cagnulein** [comment]
you can press the click button and you will see the gears changing on qz

**Comment by camster007** [comment]
They do change on QZ. Does that mean it should work in Zwift even if the connection doesn't show there?

**Comment by cagnulein** [comment]
yes exactly!

**Comment by cagnulein** [comment]
@camster007 all good?
