### ISSUE TITLE
[REQ]DeerRun Treadmill integration

### ISSUE THREAD

**Issue by ndevries84** [cagnulein/qdomyos-zwift#2621]
**Is your feature request related to a problem? Please describe.**
I bought a walking desk and the software is horrible, I would rather use your software
https://www.amazon.ca/dp/B0DFYLZ6RL

**Describe the solution you'd like**
Integrate the new treadmill

**Describe alternatives you've considered**
Use the really bad PitPat App

**Additional context**
[btsnoop_hci.log](https://github.com/user-attachments/files/17156747/btsnoop_hci.log)

Steps after loading application
It auto connects to bluetooth at startup, nothing required
Speed up 5 time (starts at .6 and goes up by .1 with each click)
Slow down 5 times
Pause
Start
Pause

**Comment by cagnulein** [comment]
Thanks i will check it ASAP!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 27 set 2024 alle 00:26 NateVan ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@ndevries84 i finished the implementation, i just need one thing little detail: which is the bluetooth name of the device? you can find it on the free app nrfconnect

let me know!

**Comment by ndevries84** [comment]
@cagnulein the bluetooth name is PitPat-T01, attached a screenshot for reference
![IMG_2808](https://github.com/user-attachments/assets/3b1a84dd-7ad1-4d8a-b959-694ec5be886c)

**Comment by cagnulein** [comment]
@ndevries84 done!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11230249404

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

Then in case I can send you also the iOS build
Let me know!

**Comment by ndevries84** [comment]
can you send the ios build?  I have to get my old android running again otherwsie

**Comment by cagnulein** [comment]
Sure 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@ndevries84 All Ok?

**Comment by ndevries84** [comment]
Sorry Just noticed this comment, yes, it worked!

**Comment by ecology-rocks** [comment]
Sorry to reopen this @cagnulein  - I was wondering if you could do the same thing for the DeerRun bike. Its Bluetooth name is PitPat-S01

**Comment by cagnulein** [comment]
Hi @ecology-rocks sure open a new ticket with a nrfconnect screenshot about your bike. Nrfconnect is a free app on the store 
Let me know!

**Comment by cchalk** [comment]
Hi I have the BA06-B1 model deerrun treadmill.

It's detected as pitpat-t01 in the app but shows no data.

Anything I can do to help get support for this treadmill?

Thanks!

![Image](https://github.com/user-attachments/assets/0c4f8671-f95d-406c-bc30-c7718a9f21e8)

**Comment by cagnulein** [comment]
it should be already compatible  could you please share a debug log? https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cchalk** [comment]
[debug-Wed_Jul_16_18_28_18_2025.log](https://github.com/user-attachments/files/21262194/debug-Wed_Jul_16_18_28_18_2025.log)

Hopefully this helps! Let me know if you need anything else.

**Comment by cagnulein** [comment]
Got the issue, I will try a patch. Do you have already an app that works
with this?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 16 lug 2025 alle 18:30 cchalk ***@***.***> ha
scritto:

**Comment by cchalk** [comment]
Wow! Great thanks! Yes I have the manufacturer provided PitPat app.

**Comment by cagnulein** [comment]
Could you please try to follow this
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device
with that app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 16 lug 2025 alle 18:39 cchalk ***@***.***> ha
scritto:

**Comment by cchalk** [comment]
[btsnoop_hci_250716_190239.log](https://github.com/user-attachments/files/21262978/btsnoop_hci_250716_190239.log)

Hopefully this works.

**Comment by cagnulein** [comment]
Thanks i will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 16 lug 2025 alle 19:27 cchalk ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
> [btsnoop_hci_250716_190239.log](https://github.com/user-attachments/files/21262978/btsnoop_hci_250716_190239.log)
> 
> Hopefully this works.

did you connect with their app to the treadmill on the same phone? because i don't see any traces of the treadmill here

**Comment by cchalk** [comment]
Yes I used the same phone.

I have 2 other logs but not sure if they worked.

[btsnoop_hci_250716_185153.log](https://github.com/user-attachments/files/21287338/btsnoop_hci_250716_185153.log)

[btsnoop_hci_250716_185655.log](https://github.com/user-attachments/files/21287382/btsnoop_hci_250716_185655.log)

**Comment by cagnulein** [comment]
yes these are ok, i'm implementing this!

**Comment by cagnulein** [comment]
@cchalk i created a new PR for you https://github.com/cagnulein/qdomyos-zwift/actions/runs/16340325703

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.

It could take several patches to make it work because I had to write a lot of code, share me a debug log from qz directly if something is not working

Let me know if you have any questions

**Comment by cchalk** [comment]
Thanks I will test when I get home.

**Comment by cchalk** [comment]
Unfortunately it doesn't work.

I have attached a debug log from the android app.

If you need anything else let me know thanks.

[debug-Thu_Jul_17_14_13_59_2025.log](https://github.com/user-attachments/files/21295461/debug-Thu_Jul_17_14_13_59_2025.log)

**Comment by cagnulein** [comment]
actually it kind of worked because now there is a communication between the
treadmill and the app! did you try to press start on the treadmill? because
i see the treadmill sending over and over 0. if you didn't press start on
the treadmill, please do it and share another debug log
thanks


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 17 lug 2025 alle ore 14:16 cchalk ***@***.***>
ha scritto:

**Comment by cchalk** [comment]
Hopefully this is better. Thanks!

[debug-Thu_Jul_17_14_34_13_2025.log](https://github.com/user-attachments/files/21296037/debug-Thu_Jul_17_14_34_13_2025.log)

**Comment by cagnulein** [comment]
wow yes i can see them! can you tell me exactly what you did in this log? i mean which speed you started and which speed you ended? no inclination right?

**Comment by cchalk** [comment]
Turn on, default starting speed is 1.0.

Then up from 1.0 to 1.1 then 1.2 and so on to 2.0

Then 2.0 down to 1.0 and then switched off.

The app is showing something now. Instead of 0 for everything.

![Image](https://github.com/user-attachments/assets/0dbc8eab-af57-4c06-a854-78f67e044ec0)

![Image](https://github.com/user-attachments/assets/41e96d91-724b-43a9-b20c-131500506bb4)

[debug-Thu_Jul_17_15_07_14_2025.log](https://github.com/user-attachments/files/21296638/debug-Thu_Jul_17_15_07_14_2025.log)

**Comment by cagnulein** [comment]
done! https://github.com/cagnulein/qdomyos-zwift/actions/runs/16346338080
let me know how it goes!

**Comment by cchalk** [comment]
Hopefully you can find something in this log.

Still can't get anything to work yet.

Anything else I can do let me know. Thanks!

[debug-Thu_Jul_17_16_25_11_2025.log](https://github.com/user-attachments/files/21298982/debug-Thu_Jul_17_16_25_11_2025.log)

**Comment by cagnulein** [comment]
ops my fault,
https://github.com/cagnulein/qdomyos-zwift/actions/runs/16348185592
fixed!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 17 lug 2025 alle ore 16:37 cchalk ***@***.***>
ha scritto:

**Comment by cchalk** [comment]
Hi, I think something has gone wrong with the build. It's showing as failed for the android app due to some QT error.

**Comment by cagnulein** [comment]
ops missing branch
https://github.com/cagnulein/qdomyos-zwift/actions/runs/16348450489

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 17 lug 2025 alle ore 16:50 cchalk ***@***.***>
ha scritto:

**Comment by cchalk** [comment]
Treadmill on and speed km/h at 1.0 is showing -0.0 
I adjusted the speed to 1.1 and the speed showed 0.1
1.2 and the speed shows -0.1
Speed 1.3 and 0.0
Speed 1.4 and 0.1
Speed 1.5 and -0.0

So getting somewhere now!

I did a git pull and switched to the DeerRun branch and compiled it on my linux computer to test before the android build is ready.

**Comment by cagnulein** [comment]
Ah I guess it's just a casting issue now, I will fix it ASAP (I'm playing
with my daughter now)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 17 lug 2025 alle 17:17 cchalk ***@***.***> ha
scritto:

**Comment by cchalk** [comment]
Debug log from the android app.

Turn on starting speed 1.0 then up speed 1.1 to 1.2, 1.3, 1.4 and 1.5 then back down again.

As you can see from the screenshots data is shown in the app.

Seems only thing not updating is the distance and speed shown incorrectly.

Thanks!

![Image](https://github.com/user-attachments/assets/89ab0d0a-2e98-4714-b5b0-1d434d601d59)

![Image](https://github.com/user-attachments/assets/f3f71b56-47fb-4480-ba08-95fde2057314)

[debug-Thu_Jul_17_17_29_45_2025.log](https://github.com/user-attachments/files/21300690/debug-Thu_Jul_17_17_29_45_2025.log)

**Comment by cagnulein** [comment]
Try this https://github.com/cagnulein/qdomyos-zwift/actions/runs/16350252352

**Comment by cchalk** [comment]
OMG! It works!

Thanks so much!

See attached screenshots for the updated data now shown 

![Image](https://github.com/user-attachments/assets/4f06566b-0ffa-4bf0-b1bc-5976f43dfe02)

![Image](https://github.com/user-attachments/assets/8889f401-1960-4d68-abef-01eaeb46448c)

**Comment by cagnulein** [comment]
Amazing!
