### ISSUE TITLE
Delay in Strava Upload and Treadmill Pace Coloring Off

### ISSUE THREAD

**Issue by PugMamma** [cagnulein/qdomyos-zwift#2933]
I updated to version 2.18.10 over the weekend and noticed, especially with tread classes a delay in workouts being sent to Strava. I took 5 walking classes and only 1 made it to Strava. I know for one class I got the email over 6 minutes after I pressed Stop on the class. It used to be within seconds after pressing Stop the class would be in Strava and now Peloton is beating the workout there and probably preventing QZ (duplicate workouts) from entering. 
I also noticed on the treadmill classes, that before the new update, the Pace Speed would light up in green when I was within the target range. Now it seems that within the range, it is green for the lowest speed and red when towards the top of the targeted range. 
[debug-logs.zip](https://github.com/user-attachments/files/18231301/debug-logs.zip)
I know it's the holidays so I don't expect any immediate response/fix. I just wanted to note the problem for now. Thanks as always and Merry Christmas/Happy Holidays!

**Comment by cagnulein** [comment]
Hi for strava I guess it's a simply server issue, I didn't change anything about it

For the speed I will check if i did something.

Just to be sure you mean 2.18.10 right? 2.18.0 is quite old and the log are about 2.18.10

**Comment by PugMamma** [comment]
Yes, 2.18.10. I'm unsure if the new power graphs are causing a delay once the class is over in QZ.

**Comment by cagnulein** [comment]
Nope, they are separated thread. Power chart are also a quite old
implemeation, so you should saw this earlier if it was the case

Anyway I will check the log just in case

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 23 dic 2024 alle 18:11 PugMamma ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
For the email I saw that there are several retries without success so I
guess this is all about this. Probably or a internet connection error or a
server errors
Let's if it happens again. Are the fit files correctly saved anyway?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 23 dic 2024 alle 18:14 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Got the chart issue, it's about new build system.
I'm going to fix in the next days
Strava and email are working fine in this build, just tried.
I will let you know, thanks for the feedback

**Comment by PugMamma** [comment]
When I get an email, the fit files are there. For the few classes that didn't make it to Strava, I've just kept the Peloton upload vs downloading and manually uploading the QZ Fit. Thanks for looking into the this! I use your app multiple times a day so always a good tester when problems arise.

**Comment by cagnulein** [comment]
ok let me know how it goes tomorrow for the email, it should be just a
fluke I hope, because on my test now everything is working (except the
charts)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 23 dic 2024 alle ore 18:43 PugMamma ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@PugMamma i checked the pace color behaviour and it was untouched. the logic is always this

if the current speed is less than the (upper speed + 0.2 km/h) and greater than (lower speed - 0.2km/h) the pace tile and the target pace tile is green, otherwise is red. could you show me a screenshot if it's not the case?

also i confirmed you that yesterday i pushed the 2.18.11 for the chart issue. I don't think it has something about email and strava, but let's see, google will review it in the next days.

Let me know how it goes today!

**Comment by cagnulein** [comment]
@PugMamma in the 2.18.10 there was also a bug about the treadmill bootcamp, fixed in the 2.18.12 #2469

**Comment by PugMamma** [comment]
[Treadmill Walk + Metric Run.zip](https://github.com/user-attachments/files/18247309/Treadmill.Walk.%2B.Metric.Run.zip)

I think some of the Pace Coloring has to do with the Treadmill metrics levels being added. Yesterday I did a normal walk and then a run that had target metrics. I set my Level to 7.
Here are some screen shots of the pacing coloring from my walk: 
![Screenshot_20241224_113615_Peloton](https://github.com/user-attachments/assets/0dfc4cc2-96a8-4663-a151-8c86b15eeed8)
![Screenshot_20241224-113620](https://github.com/user-attachments/assets/83e92a24-4651-434c-9402-92f784e65d5a)
![Screenshot_20241224_113915_Peloton](https://github.com/user-attachments/assets/62857ad4-91de-4027-a6f4-5b2cccdbe163)
![Screenshot_20241224-113919](https://github.com/user-attachments/assets/764177b8-6032-47aa-92bf-b9ddb3a0a4e6)
Me changing speed to see if I could get the colors to change:
![Screenshot_20241224-114009](https://github.com/user-attachments/assets/9d2031e3-5d35-4a15-9897-630bc634ab82)
![Screenshot_20241224-114025](https://github.com/user-attachments/assets/7feaaac1-e295-4c66-868d-d91e078ad6a3)

These are some screen shots for my Run with Metrics. I could never get the pace coloring green. It would be orange within a 0.2 of the targeted pace.
Moderate: 5.7
![Screenshot_20241224-120313](https://github.com/user-attachments/assets/1aa678b9-a1ca-466a-8ad3-d6286aef9f07)
Hard: 7.0
![Screenshot_20241224-121007](https://github.com/user-attachments/assets/aa4f16e5-2be8-4c8b-aec6-6e80e380ca81)
Very Hard: 7.7
![Screenshot_20241224-121451](https://github.com/user-attachments/assets/36ee55f5-62dc-4933-b9bd-9975d0c21319)

Just wanted to post that my row classes have been uploading to Strava like normal. I see the pop up for Strava Login Ok and then Strava Uploaded. There is just some delay with the tread classes. Unsure if it's because I do back to back classes on the treadmill vs I restart QZ for each rowing class. 
[debug-Tue_Dec_24_10_25_34_2024.log](https://github.com/user-attachments/files/18247310/debug-Tue_Dec_24_10_25_34_2024.log)

**Comment by PugMamma** [comment]
I got the new QZ update and my workouts are sending to Strava without issue. I just still have the pace coloring issues. 
I tried to enable the target power zone tile and nothing showed up. Is there a tile similar to how I have my row profile setup? For Tread Metric Classes it would say Recovery/Easy/Moderate/Challenging/Hard/Very Hard/Max?
![image](https://github.com/user-attachments/assets/abb15882-4359-4add-8ff5-e843a3f03748)

**Comment by cagnulein** [comment]
> I got the new QZ update and my workouts are sending to Strava without issue. I just still have the pace coloring issues. I tried to enable the target power zone tile and nothing showed up. Is there a tile similar to how I have my row profile setup? For Tread Metric Classes it would say Recovery/Easy/Moderate/Challenging/Hard/Very Hard/Max? 

thanks for the feedback! just add to the 2.18.13!

**Comment by cagnulein** [comment]
fixed also this @PugMamma it will be in the 2.18.13!

**Comment by PugMamma** [comment]
I'm still waiting for version 2.18.13 to come to my tablet, but found an updated chart for the treadmill metric classes. With these pace ranges vs a target speed +-0.2, this would mimic how the rower and its level paces work in QZ. 
![466643878_8751050095007214_3203250131991955882_n](https://github.com/user-attachments/assets/d4355af7-4610-4298-a96b-aa38fc22c6a1)

**Comment by cagnulein** [comment]
i don't understand: peloton changes again the way of the peloton treadmill levels?

**Comment by PugMamma** [comment]
It's the same levels, just that instead of just having one exact speed for each level, it is a range. For example under level 7 for Easy, the previous chart just listed '5.2' vs this has '5.1-5.5'. It seems the same idea from the rower levels.

**Comment by cagnulein** [comment]
Hah so I have to create a "window" around the actual target speed, got it.
I will do in the 2.18.14 or above 

Thanks

**Comment by cagnulein** [comment]
Google is even slower in these dsys

**Comment by cagnulein** [comment]
i checked and i already have the +\-0.2 on the tiles so the .13 should
already has this

let me know

the only thing is that i set a 0.2 km/h and not mi/h

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 31 dic 2024 alle 16:36 PugMamma ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
2.18.13 is live

**Comment by PugMamma** [comment]
I got to test 2.18.13 today. I did a walk and then a metric run. The pace coloring worked for the walk, but was always red during the metric run. Is it possible just the metric classes are being sent in km/h vs non metric classes are being sent in mi/h?
I had the Pace Target tile enabled, but no paces were shown. 
I do like in my QZ row classes that the Pace Target shows the ranges/window for each Target Zone. I currently have a piece of paper tapped to my treadmill with my metric paces written down. 
[debug-Wed_Jan_1_17_22_58_2025.zip](https://github.com/user-attachments/files/18287433/debug-Wed_Jan_1_17_22_58_2025.zip)
![Screenshot_20250101-173312](https://github.com/user-attachments/assets/487f491a-276c-44b9-a465-c1d73023f542)
![Screenshot_20250101-173413](https://github.com/user-attachments/assets/e98eee4a-b780-44da-9e6a-d6eb0d42f8b8)
![Screenshot_20250101-173454](https://github.com/user-attachments/assets/07e35dfe-3c9c-4cfa-94be-f5af12e71635)

**Comment by cagnulein** [comment]
> The pace coloring worked for the walk, but was always red during the metric run. Is it possible just the metric classes are being sent in km/h vs non metric classes are being sent in mi/h?

the issue is that the walking has the speed metrics directly, instead the running one has the pace intensity. now i'm modifing the code accomating the new table and i will push a new one

**Comment by cagnulein** [comment]
i will also check the target pace thing, it's for sure a bug

**Comment by cagnulein** [comment]
@PugMamma Update available

**Comment by PugMamma** [comment]
I updated QZ today and plan on taking a metric treadmill class later today. I did notice when I went to change Profiles from Rower to Horizon Tread, that most were missing within QZ. I had to go to click on the app to be able to locate them. 
![Screenshot_20250106-092608](https://github.com/user-attachments/assets/9a04d5e4-b9ed-427f-844d-d2505796def7)
![Screenshot_20250106-092634_One UI Home](https://github.com/user-attachments/assets/61b40f98-4f9c-4bff-8a52-4ff817840732)

**Comment by cagnulein** [comment]
There profiles are limited, it's an android limitation. Only on qz directly you can see them all

**Comment by PugMamma** [comment]
Tested QZ version 2.18.14. The Target Pace tile ranges were not lining up with the call outs. 
Is the Target Speed Tile able to be enabled during treadmill workouts too?

[debug-Mon_Jan_6_18_34_47_2025.log](https://github.com/user-attachments/files/18327370/debug-Mon_Jan_6_18_34_47_2025.log)

Screenshots from the metric run. The Target Pace tile displayed information, but the ranges were way off:
![Screenshot_20250106-184450](https://github.com/user-attachments/assets/3a69eb7d-7f9d-42f3-89df-f323d401893e)
![Screenshot_20250106-184856](https://github.com/user-attachments/assets/6f9df6dc-1980-4ad5-8260-913cf709fba1)

From non metric (normal walk). Unsure if the target paces are supposed to match up from what is provided from Peloton. 
![Screenshot_20250106-183741](https://github.com/user-attachments/assets/fb5ab2e0-d12a-4fb3-9708-2d21c385241b)

**Comment by cagnulein** [comment]
Yes target speed can be enabled as well! 

I will check the log, in order to accommodate the target pace ranges i had to do a lot of modification so maybe something went wrong?

**Comment by cagnulein** [comment]
got the issue @PugMamma the target pace is always on m/km 
enable the target speed. if it's ok, the fix it's easy
let me know!

**Comment by PugMamma** [comment]
I had the Target Speed Tile enabled in the photo above, but it just listed 0.0 the whole time.

**Comment by PugMamma** [comment]
Thanks for the explanation. I will keep the speed force disabled (I prefer to be in control of speed vs the auto incline). If the target Pace can be fixed to miles/hour that would be great!

**Comment by PugMamma** [comment]
I had my Pace at 11:19 (minutes per mile) and QZ showed a range of 4:32-4:12. Based on this chart the km range would 7:19-6:46. Guess I'll just see if the numbers match up when the update comes through. 
![image](https://github.com/user-attachments/assets/71228d7d-17e4-4af3-b50f-b2637284691a)

**Comment by cagnulein** [comment]
Version online

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 7 gen 2025 alle 17:01 PugMamma ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @PugMamma any news?

**Comment by PugMamma** [comment]
Sorry I was visiting my parents this weekend, but was able to test tonight. It seems the Target Pace tile is still showing minutes per km vs minutes per mile. Looking at the km vs mile chart, that seems to be the issue.
Also can the recovery zone lower limit go down to 1.0 mph or 60 minutes per mile. There are some drills I take at 1.5 speed. 
[debug-Mon_Jan_13_19_35_11_2025.log](https://github.com/user-attachments/files/18405273/debug-Mon_Jan_13_19_35_11_2025.log)
![Screenshot_20250113-193915](https://github.com/user-attachments/assets/7736e9f9-a3c4-4ad5-9f6e-66149b53430a)
![Screenshot_20250113-193730](https://github.com/user-attachments/assets/9a77da0f-c49e-4727-914f-d7d47690d15b)
![Screenshot_20250113-194216](https://github.com/user-attachments/assets/1f17afc2-bbad-46c5-9d23-18a96404ab73)
Minutes per Km and minutes per mile chart: https://www.depicus.com/swim-bike-run/pace-conversion-chart

**Comment by cagnulein** [comment]
Thanks I will check it again!

**Comment by cagnulein** [comment]
@PugMamma could you please also add a screenshot with the target speed tile enabled? Thanks!

**Comment by cagnulein** [comment]
ok i guess i found the issue. there was a miles conversion in the parsing of the speeds. i'm uploading a new one! thanks for the continuos feedbacks!

**Comment by PugMamma** [comment]
> @PugMamma could you please also add a screenshot with the target speed tile enabled? Thanks!

Do you still want a screenshot of the target speed tile enabled? Also would you want the auto speed tab enabled as well to get the tile to display data?

**Comment by cagnulein** [comment]
No I guess it's useless now, I already got the issue. Google is reviewing

**Comment by cagnulein** [comment]
Version online

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 14 gen 2025 alle 17:51 PugMamma ***@***.***> ha
scritto:

**Comment by PugMamma** [comment]
Target Pace is working for metric classes! Thank you for making QZ such a great app. 

![Image](https://github.com/user-attachments/assets/ed5448fe-f3f9-4b33-a730-453cf1b88857)

![Image](https://github.com/user-attachments/assets/05bd97e4-efc9-411b-be38-f20812070e66)

The only small thing I noticed is some paces on the cusp of the range zone would show up orange. Even though for Hard I was at 8:13 pace (target range 8:49-8:13) and Very Hard I was at 8:06 pace (target pace 8:06-7:24). Assuming it's something with the code and calculation and overall thrilled to have the correct ranges in minutes/mile show up. 

![Image](https://github.com/user-attachments/assets/ceaecc17-d21c-458a-acc1-6cbae6bbf331)

![Image](https://github.com/user-attachments/assets/4015e7f5-f924-4771-841c-01d0db43dabd)

**Comment by cagnulein** [comment]
Amazing! Thanks for the continuous feedbacks! Let me check I guess it's only about a > instead of a >=

**Comment by cagnulein** [comment]
@PugMamma for the last issue: do you have also the debug log?

**Comment by PugMamma** [comment]
Metric class is the 15 minute intervals run class (2nd class in the log). 
[debug-Fri_Jan_17_09_59_36_2025.zip](https://github.com/user-attachments/files/18466105/debug-Fri_Jan_17_09_59_36_2025.zip)

**Comment by cagnulein** [comment]
Thanks, I'll check it out!


Il giorno sab 18 gen 2025 alle 22:09 PugMamma ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
confirmed, it's just a rounding thing. I was looking for a speed greater than 11.90912 km/h and you were at 11.9091 km/h
let me try to add a window

**Comment by cagnulein** [comment]
done @PugMamma it will be in the next one

**Comment by cagnulein** [comment]
@PugMamma 2.18.18 online! I hope it will be the final one

**Comment by PugMamma** [comment]
No issues found! Took the perfect class to test today with (has all 7 target zones) and QZ colors matched up to each zone. I made sure to try the lower and upper limit for each zone. Thank you for all the work you did.

**Comment by cagnulein** [comment]
Glad to hear it!
