### ISSUE TITLE
[BUG] Proform Trainer 8.0 No Bluetooth control

### ISSUE THREAD

**Issue by lucstp66** [cagnulein/qdomyos-zwift#3017]
**Describe the bug**
I have try to use different config from other Treadmill and being able to see the speed and other data from it
but unable to change the speed or else with Qz.

**To Reproduce**
As requested I started the App IFIT on my tablet wit debug mode activated for  Bluetooth.
I started a free run on Ifit and from the warming stage
1-Changed the slope
2- changed the speed,

Ended the Warming stage and started the run...
the Ifit changed itself the slope and speed,
after a few second a stopped the activity.

**Desktop (please complete the following information):**
 - OS: [Android]

**Smartphone (please complete the following information):**
 - Device: [Galaxy Tab S7]
 - Model SM-T870
 - OS: [Android 13]
 - One UI 5.1.1
 - Kernel Version [4.19.113-27114284]

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
[bugreport-gts7lwifixx-TP1A.220624.014-2025-01-09-16-53-12.zip](https://github.com/user-attachments/files/18368932/bugreport-gts7lwifixx-TP1A.220624.014-2025-01-09-16-53-12.zip)

**Additional context**

**Comment by lucstp66** [comment]
**Smart Phone running Qz**

Samsung Galaxy S23 Ultra
Model : SM-S918W
OS Android
Version 14, UI 6.1

**Treadmill**
Pro-Form Trainer 8.0
Version 80.198
Speed (MPH) and Slope Max. 12

**Comment by cagnulein** [comment]
thanks i will check it asap

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/12709804260
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by lucstp66** [comment]
hi, thank you for the update.
I try it and there is an issue with webvision, adnroid ask me to downgrat to the original version and Qz seem to be more stable. Still crashing.
I able to change speed and slope with it but randomly it crash.
for. policy for watt, ftp zone and average watt are red at start and then get BW. but caracters are out or box range and too big.
If I let Qz running its close itself after a few second.
I will  add some screen shot.

**Comment by cagnulein** [comment]
what is webvision? what do you mean still closing? i need a debug log to understand what you are talking about :) https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by lucstp66** [comment]
![Screenshot_20250110_102610](https://github.com/user-attachments/assets/9fde1be1-a566-425c-bccd-40e487c8f7da)
![Screenshot_20250110_102539](https://github.com/user-attachments/assets/906846bc-c8e5-4259-a85c-762162137d10)

**Comment by cagnulein** [comment]
Create a debug log and I will check it! https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Attach it here

**Comment by lucstp66** [comment]
Qz folder is empty of log or text files,
the app is not retining my setting when selecting Proform Traner 8 on the list.
Android advertise me that Qz crashed many time.

Thank you.

**Comment by cagnulein** [comment]
Are you able to create a bug report following this https://developer.android.com/studio/debug/bug-report?hl=it

**Comment by cagnulein** [comment]
> the app is not retining my setting when selecting Proform Traner 8 on the list.

saw this too, i'm fixing it

**Comment by cagnulein** [comment]
> the app is not retining my setting when selecting Proform Traner 8 on the list.

fixed https://github.com/cagnulein/qdomyos-zwift/actions/runs/12715156154

**Comment by lucstp66** [comment]
Hi,
Ok now my setting are renained for the treadmill model.
Still closing after less then a minutes.
Number on some tile are too big.
About the app causing issue see the picture.

Thank you :)
![Screenshot_20250110_153746_Device care](https://github.com/user-attachments/assets/abfd5a0f-add9-4bca-9fbc-9b5488c50fd1)

**Comment by cagnulein** [comment]
Yes please create a bug report as I said above
Or create a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by lucstp66** [comment]
[bugreport-gts7lwifixx-TP1A.220624.014-2025-01-11-10-51-44.zip](https://github.com/user-attachments/files/18386452/bugreport-gts7lwifixx-TP1A.220624.014-2025-01-11-10-51-44.zip)

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 11 gen 2025 alle 17:06 lucstp66 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
thanks @lucstp66 could you please add also a debug log of qz when it crashes? thanks

**Comment by lucstp66** [comment]
Here a debug log from my phone. On my tablette I dont have access to the Qz folder.
[Car-Maintenance-Reminder-Data.csv](https://github.com/user-attachments/files/18387057/Car-Maintenance-Reminder-Data.csv)

**Comment by lucstp66** [comment]
Its on it now, on then previous comment...

**Comment by cagnulein** [comment]
that's a fit file, i need a debug log (the one with the debug prefix in the name)
thanks

**Comment by lucstp66** [comment]
There is no other files ont root folder of Qz.
The app is closing very fast... is this a license issue Or timeout on the app?

**Comment by cagnulein** [comment]
It's a 15 minute trial that you can restart as many as you want 

Did you enable the debug log setting in the experimental settings?

In order to do so simply disable Bluetooth first, enable the debug log , close qz, and enable back Bluetooth and restart qz

**Comment by lucstp66** [comment]
Oups ok, here it is ;)
[debug-Sun_Jan_12_11_19_01_2025.log](https://github.com/user-attachments/files/18390137/debug-Sun_Jan_12_11_19_01_2025.log)

**Comment by cagnulein** [comment]
Ok Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 12 gen 2025 alle 17:21 lucstp66 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
> Hi, Ok now my setting are renained for the treadmill model. Still closing after less then a minutes. Number on some tile are too big. About the app causing issue see the picture.
> 
> Thank you :) ![Screenshot_20250110_153746_Device care](https://private-user-images.githubusercontent.com/194436656/402145272-abfd5a0f-add9-4bca-9fbc-9b5488c50fd1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3MDE5ODYsIm5iZiI6MTczNjcwMTY4NiwicGF0aCI6Ii8xOTQ0MzY2NTYvNDAyMTQ1MjcyLWFiZmQ1YTBmLWFkZDktNGJjYS05ZmJjLTliNTQ4OGM1MGZkMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMlQxNzA4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjA2MDk3MmUyYTA2ODEyM2RlNTE3YjM5Y2I0MDA3ZjljZWEwNGJiNmNiMDBlMjQzMjc3MWM5YTcwY2NkZmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ETpUjhzmmQN7Hh39JXcX-qOrSG5JldtdqK5C6dn5XUg)

i was checking again this and this is probably the issue. did you try to uninstall the webview?

**Comment by lucstp66** [comment]
Yes, as this is à system app i just downgraded to original release. The error dissapeared but Qz continued to close. I try to install the new dev version of webview. No issue With it but Qz continue to closed.

**Comment by cagnulein** [comment]
From the bug report it was reporting the web view issue. Did you uninstall it after taking the bug report?

**Comment by lucstp66** [comment]
Not shure but I think yes bécasse u correctement the save setting after... I can try it to be shure.

**Comment by lucstp66** [comment]
I have retry the original app from app store and the app stay open forever until I close it.

**Comment by cagnulein** [comment]
That's strange. Ok I will build it directly instead of using the github actions, let's see if it's different 


send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
hi @lucstp66 are you still using the app? could you please tell me the firmware version of your treadmill? is qz still able to control speed and incline from the app?

**Comment by lucstp66** [comment]
Hey hello ;)

Yes I have used it a few time on the last weeks.
I will check this and let you know.

Luc

Le sam. 14 mars 2026, 05 h 33, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
Great, no rush, just checking :)

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno sab 14 mar 2026 alle 15:43 lucstp66 ***@***.***> ha
scritto:

**Comment by lucstp66** [comment]
Iam able to control the speeb and slope witth Qz but Zwift cannot.
also Heart rate (Qz read nothing) and Fan (Low medium High) on my treadmill
is not working.

Regards,

Luc

Le sam. 14 mars 2026, 10 h 45, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
with zwift you need to follow this https://github.com/cagnulein/qdomyos-zwift/wiki/Can-Zwift-control-speed-and-or-inclination-of-my-treadmill%3F
