### ISSUE TITLE
[BUG] Concept2 Rowers connecting but tiles do not update.

### ISSUE THREAD

**Issue by schmidgit** [cagnulein/qdomyos-zwift#3503]
**Describe the bug**
I am able to connect to both of 2 different Concept2 Rowers in my work gym (with PM5) but the tiles do not update with any data once I start the workout. These rowers both worked previously. I tried rebooting my phone and then uninstalling/reinstalling the app, all to no avail. At the end of the workout, it uploads an essentially empty 'Ride' workout  to Strava and the QZ activity shows an empty ride summary as well.

**To Reproduce**
1. Begin rowing on C2.
2. Open QZ app
3. The rower is auto-detected and a workout starts
4. None of the tiles show any data.

**Expected behavior**
Previously, the tiles update to match what is shown on the rower.

**Screenshots**

See Facebook post: https://www.facebook.com/groups/149984563348738

**Desktop (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
 - Device: Google Pixel 9
 - OS: Android
 - Version: 16

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by schmidgit** [comment]
[debug-Mon_Jun_23_15_10_37_2025.log](https://github.com/user-attachments/files/20871911/debug-Mon_Jun_23_15_10_37_2025.log)

**Comment by schmidgit** [comment]
I checked under Rower Options » FTMS Rower and it just shows "Disabled", so I don't that is the problem.

**Comment by cagnulein** [comment]
Got the issue, it's about a modification thst I did for another pm5 user.
I will revert back and I will send it ASAP
Thanks for the feedback

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 24 giu 2025 alle 04:31 schmidgit ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done! @schmidgit please send me an email to roberto.viola83 at gmail.com so i will send you the new beta.
The new ios version will show you a popup about fixing this scenario and to restart qz to apply the changes. Then it should work as before.
Sorry for the inconvenience

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/actions/runs/15846775574/artifacts/3390827297

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link . In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.

This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by schmidgit** [comment]
@cagnulein Ok I uninstalled, then downloaded from your link and extracted the APK, then installed it. I just tried it at my work gym and it appears to still not work. The very first time I tried, it auto-connected to the rower but had the same problem where the tiles were not updating. I then went into settings and saw the rower was listed under FTMS Rower, so I changed that to Disabled. It restarted the app, and after that point, I never got QZ to connect to the rower again whether I selected it in FTMS Rower or set that to Disabled. Attached are some logs. The first time I went into settings, the debug logs were not enabled by default, so I don't think it captures that first run when the rower was actually connected.

[debug-Tue_Jun_24_12_21_04_2025.log](https://github.com/user-attachments/files/20888382/debug-Tue_Jun_24_12_21_04_2025.log)
[debug-Tue_Jun_24_12_21_54_2025.log](https://github.com/user-attachments/files/20888384/debug-Tue_Jun_24_12_21_54_2025.log)
[debug-Tue_Jun_24_12_22_24_2025.log](https://github.com/user-attachments/files/20888383/debug-Tue_Jun_24_12_22_24_2025.log)
[debug-Tue_Jun_24_12_23_35_2025.log](https://github.com/user-attachments/files/20888381/debug-Tue_Jun_24_12_23_35_2025.log)

Just a reminder, I am running Android 16 on a Pixel 9 phone.

**Comment by cagnulein** [comment]
That's right it must be on ftms rower, qz is setting it automatically.
Please try again with ftms rower set to it.
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 24 giu 2025 alle 19:31 schmidgit ***@***.***>
ha scritto:

**Comment by schmidgit** [comment]
I did, I tried every which way I could think to try.... I will go try again after I return from my lunch break.

**Comment by cagnulein** [comment]
Ok let me check the log

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 24 giu 2025 alle 19:36 schmidgit ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
log checked the main issue is that when you have the ftms rower set to the rower the rower is not broadcasting like it's connected somewhere else. could you check it? maybe restart the rower? also you can check with the nrfconnect app if you can see it before starting qz

let me know

**Comment by schmidgit** [comment]
Same behavior, it connects but tiles do not update. Here are images and a log. It does appear under FTMS Rower.

[debug-Tue_Jun_24_17_15_01_2025.log](https://github.com/user-attachments/files/20893431/debug-Tue_Jun_24_17_15_01_2025.log)

![Image](https://github.com/user-attachments/assets/a40514fb-ebcd-476e-bec6-c091e8163470)

![Image](https://github.com/user-attachments/assets/a50bd375-015c-48c0-b024-057c4fc52494)

![Image](https://github.com/user-attachments/assets/8ab7f441-8f83-4935-93bf-400dd894154d)

**Comment by schmidgit** [comment]
Also, I just uninstalled and re-installed from the APK you sent me and it behaves the same.

I also installed nRF Connect and found the device and connected. Both when I was connected with that *and* when connected with QZ, the rower shows that it is connected on the PM5. Here are some more screenshots. I also did all this on another rower (my gym has 2 identical ones) and everything was the same. Both of these rowers previously just worked, I never had to change anything in settings, just a few weeks ago.

![Image](https://github.com/user-attachments/assets/ae29c8c2-a106-4101-b0c0-22aa76bce55d)

![Image](https://github.com/user-attachments/assets/539a23c7-c8c1-48af-b8c6-b224b08d20d4)

![Image](https://github.com/user-attachments/assets/c565c862-af4c-41a4-a512-2d9ba3f888e5)

**Comment by schmidgit** [comment]
The log file shows the same `critical` error as before with refused connection, only the port is different now.

**Comment by cagnulein** [comment]
Thanks https://github.com/user-attachments/files/20893431/debug-Tue_Jun_24_17_15_01_2025.log but in this log the ftms rower is set to disabled. Maybe you have another one?
Thanks

**Comment by schmidgit** [comment]
I don't know what to say. When I open the settings and look under `Rower Options` at the `FTMS Rower` selection it shows the `PM5 430131687` as being selected. It is right there in the second screenshot showing 5:15 on my phone, which is the time on the log file. 

Is there a way to record my exact sequence of clicks showing me opening the app, connecting to the rower, nothing happening, opening settings and seeing that it is selected in the `ftms rower` option? I'm not sure how to prove it any other way.

**Comment by cagnulein** [comment]
Send me all of the logs so I will pickup the right one. You can zip all of
them

Thanks, today I'm out of town I will check them tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 25 giu 2025 alle 08:07 schmidgit ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Any news @schmidgit ?
