### ISSUE TITLE
[BUG] QZ Android Sends Data Even Without Pedaling

### ISSUE THREAD

**Issue by andrelima-arch** [cagnulein/qdomyos-zwift#3763]
After 60 to 90 minutes of training, the QZ app on Android starts sending incorrect data.
The power and cadence data begin to have spikes, and even without pedaling it continues to send data to Zwift.

I use the trainer on a Garmin and on QZ Android at the same time, only on Android I had this problem.
The solution was to disconnect from Zwift and reconnect, and it returned to normal.
I noticed this happens both in ERG mode and in Free ride mode.

I tried using the WiFi connection "Wahoo KICKR 0000 33" but it had cadence issues (but I saw it's being fixed).
I tried accessing the log folder, but my Android doesn't allow it, I'll see if on Saturday when I train again, I can add the log here.

My smart trainer is a Thinkrider X2 Max and I'm using the Bluetooth connection from a Samsung S20FE, my desktop is a Dell G15.

**Comment by cagnulein** [comment]
share a log and I will check it https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

also if you aren't already, join the beta from here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift and update the app on the store, i already fixed something like that on android

**Comment by andrelima-arch** [comment]
Hello.

Here, today I used the beta version android.
Some of the problems happened.

When connecting to WiFi, cadence spikes.

With the Bluetooth connection, I was inactive for a while at the beginning of the training, with everything connected.
And there was a problem sending data to zwift.

With the Bluetooth connection, when you stop pedaling, the cadence increases to very high values.

I was unable to add the files directly here.
Link to google drive.
https://drive.google.com/drive/folders/1CI8mri4ktWKeQYgL95pfZDBslWUQNrOi?usp=sharing

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 ott 2025 alle 18:04 andrelima-arch <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Note for me

sˆ¡b. out. 18 07:29:10 2025 1760783350476 Debug:
../src/devices/tacxneo2/tacxneo2.cpp void
tacxneo2::characteristicChanged(const QLowEnergyCharacteristic &, const
QByteArray &) "Current Cadence: " 7507.14 0 190 -1555 1024 0 2579


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 ott 2025 alle 18:31 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I guess it's the same that I fixed here

ssues connecting zwift play with thinkrider max 2 (Issue #3758) (#3759)


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 ott 2025 alle 18:35 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@andrelima-arch Please download this https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly-2025-10-17/android-debug.apk


Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link. In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by andrelima-arch** [comment]
Hello, today I tested the app, the version from 10/17.

It worked much better in Free Ride, I'll test it in ERG mode.

There is still a problem with peak cadence, but only when you stop pedaling.
During pedaling, the cadence remains constant.

Using a WiFi connection, I had no problem with power numbers.

I noticed that it works better on a WiFi connection.
Using Bluetooth, it takes a long time to connect.

Log:
https://drive.google.com/drive/folders/1QQTTD4dT6U7BKMtjRMJbhXlVsO0plaPn?usp=sharing

**Comment by cagnulein** [comment]
ok i fixed also that cases https://github.com/cagnulein/qdomyos-zwift/actions/runs/18873352103

Let me know!

**Comment by andrelima-arch** [comment]
Hello, I did a workout today, everything is working ok.
Thanks for the adjustments.

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno mer 29 ott 2025 alle 14:59 andrelima-arch <
***@***.***> ha scritto:
