### ISSUE TITLE
[BUG] App closes after Bluetooth connection

### ISSUE THREAD

**Issue by v1carter** [cagnulein/qdomyos-zwift#3807]
**Describe the bug**
Once the app finds the Bluetooth the app closes with no error and see BLU on bike trainer
(Domoys initial bike trainer with Bluetooth )

**To Reproduce**
1. Bluetooth is on
2. Open qz fitness app
3. Wait for Bluetooth connection
4. See app q domoys closes

**Expected behavior**
The app stays open after Bluetooth connection so can be tracked

**Screenshots**
If applicable, add screenshots to help explain your proble

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/c3436446-4731-42ec-9965-2fc0e83fb821" />

m.

**Smartphone (please complete the following information):**
 - Device: pixel 9a
 - OS: android 16
 - Version 2.20.11

**Append a debug log**

[debug-Wed_Oct_22_18_26_00_2025.log](https://github.com/user-attachments/files/23148207/debug-Wed_Oct_22_18_26_00_2025.log)
[debug-Wed_Oct_22_18_25_55_2025.log](https://github.com/user-attachments/files/23148208/debug-Wed_Oct_22_18_25_55_2025.log)
[debug-Wed_Oct_22_18_03_17_2025.log](https://github.com/user-attachments/files/23148209/debug-Wed_Oct_22_18_03_17_2025.log)
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks I guess I already fixed 

https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly-2025-10-17/android-debug.apk


Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by v1carter** [comment]
Thank you, with the trial QZ apk still see BLE on trainer and then QZ abruptly stops
Maybe something with my phone, I hope to try on another device

**Comment by cagnulein** [comment]
share a debug log with this apk, it works with another user, so let me try to understand this

**Comment by cagnulein** [comment]
sorry, my fault, check this https://github.com/cagnulein/qdomyos-zwift/actions/runs/18810516257/artifacts/4372643494

**Comment by v1carter** [comment]
Thank you, the latest apk fixes app closing - but stats are not tracked
[0QZ-backup-Fri Oct 31 12_25_11 2025.zip](https://github.com/user-attachments/files/23266869/0QZ-backup-Fri.Oct.31.12_25_11.2025.zip)
<img width="375" height="667" alt="Image" src="https://github.com/user-attachments/assets/625860da-a9b8-43b7-9866-8f63ba617936" />

**Comment by cagnulein** [comment]
unfortunately this is a fit file, I need a debug log file. It has the debug prefix in the file name

**Comment by cagnulein** [comment]
unfortunately this is a fit file, I need a debug log file. It has the debug prefix in the file name

**Comment by v1carter** [comment]
[debug-Fri_Oct_31_17_32_15_2025.log](https://github.com/user-attachments/files/23267234/debug-Fri_Oct_31_17_32_15_2025.log)

**Comment by cagnulein** [comment]
thanks i will check it ASAP

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno ven 31 ott 2025 alle 18:37 v1carter ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Got the issue. I did a patch https://github.com/cagnulein/qdomyos-zwift/actions/runs/18983338946


Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@v1carter worked?

**Comment by v1carter** [comment]
![Screenshot_20251111-113500~2.png](https://github.com/user-attachments/assets/0a0350e0-741b-4163-9a96-d165c5c3b4f4)



Trial app works as expected, thank you

**Comment by cagnulein** [comment]
that's great! let me know if you want to unlock it!

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mar 11 nov 2025 alle ore 12:44 v1carter ***@***.***>
ha scritto:
