### ISSUE TITLE
[REQ] QZ should listen to start / stop signals from the workout player

### ISSUE THREAD

**Issue by rajivgandhi1** [cagnulein/qdomyos-zwift#3876]
**Is your feature request related to a problem? Please describe.**
When using training apps (eg. mywhoosh / kinoway / zwift / rouvy), it is inconvenient & in-cohesive for users to switch to QZ app to start / stop workouts since QZ controls are not accessible as anchored screen overlays and QZ only records activities & updates to Strava / Peloton when using native start / stop controls.

**Describe the solution you'd like**
QZ should listen to start / stop signals from the workout player because it has a universal overlay accessible on the screen while using any app.

**Describe alternatives you've considered**
Alternative is to switch to QZ app, press controls and switch back to training app.

**Additional context**
The test treadmill is Nordictrack commercial 1750 (Model no NTL17125.0)

**Comment by cagnulein** [comment]
Thanks I will try to add it ASAP

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno dom 16 nov 2025 alle 09:42 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done @rajivgandhi1 https://github.com/cagnulein/qdomyos-zwift/actions/runs/19426566479

you can use the android build in the link (check at the bottom of the page in about 1 hour). 

@victorypoint  also for reference, i guess it could be useful also for you

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/19427391485

**Comment by rajivgandhi1** [comment]
@cagnulein The build seems failed.

**Comment by cagnulein** [comment]
No it's fine. Download from here
https://github.com/cagnulein/qdomyos-zwift/actions/runs/19427391485/artifacts/4587583026


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mar 18 nov 2025 alle 03:26 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by rajivgandhi1** [comment]
Does not work. Pressing quick start / end on workout player does not reflect on qz

**Comment by cagnulein** [comment]
Share a debug log so I can check it
Thanks

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mar 18 nov 2025 alle 07:24 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by rajivgandhi1** [comment]
Will provide tomorrow.

**Comment by rajivgandhi1** [comment]
Attached (qz incline gain set to 0.5):

1. Played first run with workout player (speed: 1 mph, incline 0). start/stop did not register with qz
2. Second run with zwift. Workout incline was supposed to be 1%, speed: 3.5mph. 
- when run was "quickstart" using workout overlay, speed was at 1mph, incline at 0% (note qz did not correct them). Display showed 0%
- Incline was set manually to 2 % using workout overlay -> zwift override it to -0.5% (in other subsequent run it override to -3%). Display showed 0%
3. Third run with zwift. Workout incline was supposed to be 1%, speed: 3.5mph. 
- when run was "quickstart" using workout overlay, speed was at 1mph, incline at 0% (note qz did not correct them). 
- Speed was set manually to 2 mph using workout overlay -> zwift did not do anything. 
- Speed was set manually to 4 mph using workout overlay -> zwift did not do anything

[debug-Mon_Nov_17_22_39_13_2025.log](https://github.com/user-attachments/files/23599168/debug-Mon_Nov_17_22_39_13_2025.log)

[debug-Mon_Nov_17_22_47_19_2025.log](https://github.com/user-attachments/files/23599171/debug-Mon_Nov_17_22_47_19_2025.log)

**Comment by cagnulein** [comment]
> * Incline was set manually to 2 % using workout overlay -> zwift override it to -0.5% (in other subsequent run it override to -3%). Display showed 0%

yes it's what zwift is sending, zwift shows an average instead it sends via api the actual value, that's the mismatch. anyway the applied one it's the real value



> 5\. Third run with zwift. Workout incline was supposed to be 1%, speed: 3.5mph.
> 
> * when run was "quickstart" using workout overlay, speed was at 1mph, incline at 0% (note qz did not correct them).
> * Speed was set manually to 2 mph using workout overlay -> zwift did not do anything.
> * Speed was set manually to 4 mph using workout overlay -> zwift did not do anything

on workout speed and incline are not being sent from zwift. you have to load a zwo manually in zwift

> 1. Played first run with workout player (speed: 1 mph, incline 0). start/stop did not register with qz

i'm adding some new debug log to understand the issue, new build is coming

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/19457739316

**Comment by rajivgandhi1** [comment]
Not sure I understand your response:
1. Start use case: When workout was initiated both on zwift and started via workout overlay, qz never intercepted the start, zwift never really set the intial treadmill speed/incline correctly to 3.5 mph, 1% incline
2. Incline use case: When incorrect (not matching zwift workout) incline changes (through workout overlay). Zwift detected the drift and sent correction. What I am reporting is that it did not make the right correction
3. speed use case: Incase of speed changes (through workout overlay), zwift never really even attempted to correct the drift
4. end use case: When workout was ended via workout overlay (and on zwift), qz never intercepted the stop.

Do you not see any issue with the above observations? As a user, these are all incorrect behaviors.

P.S. Incline display on zwift in all the above use cases was 0.

**Comment by cagnulein** [comment]
> 1. Start use case: When workout was initiated both on zwift and started via workout overlay, qz never intercepted the start, zwift never really set the intial treadmill speed/incline correctly to 3.5 mph, 1% incline

yes i created that bnew build in order to have some new logs about the start thing



> 2\. Incline use case: When incorrect (not matching zwift workout) incline changes (through workout overlay). Zwift detected the drift and sent correction. What I am reporting is that it did not make the right correction

I understood it, and what I said is that the incline forced on qz, it's the one sent from zwift via api. It's not matching because zwift shows the average in the display but sends the actual one via api



> 3\. speed use case: Incase of speed changes (through workout overlay), zwift never really even attempted to correct the drift

yes for the speed you need to load the zwo in qz too as stated in the wiki 

> On workout, you need to load the ZWO file of the workout in QZ also, then QZ will set the speed and inclination



> 4\. end use case: When workout was ended via workout overlay (and on zwift), qz never intercepted the stop.

same as 1.



> Do you not see any issue with the above observations?

i see all of them and there is an answer  for all of them  :)



> P.S. Incline display on zwift in all the above use cases was 0.

yes but zwift sends instead different values

**Comment by rajivgandhi1** [comment]
I think you have misunderstood the incline use case:
1. When started (workout overlay):
- zwift program has target incline of 1%
- **treadmill is running at 0%**
- zwift display shows 0%

2. When changed (workout overlay to say 2%):
- zwift program has target of 1%
- treadmill adjusts to 2% as directed by workout overlay
- **zwift display shows 0%**
- **1-2 seconds later, the treadmill incline auto-adjusts to 0.5% (sometimes -3%)**
- **zwift display shows 0%**

The bolded behaviours are incorrect.

can you please point to the instructions to configure the zwo file?

**Comment by cagnulein** [comment]
are both zwift workout? if yes autoincline must be disabled because you need to load the zwo file. Auto inclination via zwift api reads the real inclination of the world, not the one request from the workout

**Comment by cagnulein** [comment]
zwo file can be created manually or it should be inside the windows directory of zwift usually 
i'm also adding the workout editor inside qz https://github.com/cagnulein/qdomyos-zwift/pull/3760

**Comment by cagnulein** [comment]
https://www.zwiftworkout.com/editor/evh2kmn0dcm

**Comment by rajivgandhi1** [comment]
In my results in this link: https://github.com/cagnulein/qdomyos-zwift/issues/3876#issuecomment-3545740308

There were 3 runs:
1. One using workout player only (no zwift workout)
2. zwift workout
3. zwift workout

- Start sync / speed / incline drifts are for zwift workouts
- Start / stop signal sync with qz is a qz problem
- Volume overrides are a qz problem

**Comment by rajivgandhi1** [comment]
Frankly, it seems there is too much complication syncing across various apps:
1. Workout player
2. qz
3. zwift
4. ZWO file

At this point, I would just narrow my wishlist to the following:
1. Fix the volume override issue
2. this git issue - which is qz should intercept start/stop from workout player.
3. strava account per profile

I will provide a log tomorrow for that test

**Comment by cagnulein** [comment]
ok so let me know how it goes the new build. unfortuantely yes zwift doesn't make a simple way to get the workout yet. I have in the todo list to read somehow these values but i didn't do yet

**Comment by rajivgandhi1** [comment]
I installed the debug version. Logs attached.

Use case:
1. Enabled debug log
2. press quick start on workout overlay
3. hit pause
4. hit end 
5. press quick start on workout overlay
6. hit pause
7. hit resume
8. hit end 

Expected:
1. quick start / pause / resume / end signals should be reflected in the qz app.

Actual:
1. quick start / pause / resume / end signals were not reflected / intercepted in the qz app.


[debug-Tue_Nov_18_16_00_00_2025.log](https://github.com/user-attachments/files/23615865/debug-Tue_Nov_18_16_00_00_2025.log)

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mer 19 nov 2025 alle 01:05 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@rajivgandhi1 i'm still seeing version 2.20.11 in your log. the new version has 2.20.15.
are you sure you are installing and using the correct version?

**Comment by rajivgandhi1** [comment]
I had installed this one:
https://github.com/cagnulein/qdomyos-zwift/actions/runs/19457739316/artifacts/4598435895

**Comment by cagnulein** [comment]
It's strange that it still the .11 so
I will decompile it tomorrow to be sure and I will let you know

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mer 19 nov 2025 alle 17:46 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i checked and the apk that you linked is the 2 . 2 0 . 1 5 version

maybe you forgot to uninstall the previous version before installing the new one?

**Comment by rajivgandhi1** [comment]
Defects:
1. It seems QZ installer was **not able to update and had failed**. 
2. So, I took a backup of settings, uninstalled, re-installed, restored settings. **While settings import claimed success, it did not really reflect**. So I had to reconfigure everything.
3. I re-ran the test but the **start/stop intercept did not work**. Logs attached.

[debug-Thu_Nov_20_11_53_57_2025.log](https://github.com/user-attachments/files/23662183/debug-Thu_Nov_20_11_53_57_2025.log)

**Comment by cagnulein** [comment]
Did you save the settings before uninstalling? You can put the file here so
I can check if it's right

I will check the log tomorrow

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno gio 20 nov 2025 alle 20:59 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by rajivgandhi1** [comment]
Yes (attached) - I had exported settings, made a copy. (one more potential defect, is qz uninstall should not delete backup data - in my case, I thought I was lucky I had made a backup)

[settings_Rajeev_20251120112542.qzs.txt](https://github.com/user-attachments/files/23662381/settings_Rajeev_20251120112542.qzs.txt)

**Comment by cagnulein** [comment]
Seems right, did you use the other folder button to import it and it was
outside the qz folder?

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno gio 20 nov 2025 alle 21:05 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by rajivgandhi1** [comment]
I tried restoring & importing settings file from the qz files folder - it did not let me copy there.

So I had to restore from other folder.

**Comment by cagnulein** [comment]
Yes it seems the right way to do it.
Anyway let's check first the start and stop issue and then I will try to
fix the rest

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno gio 20 nov 2025 alle 21:08 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by rajivgandhi1** [comment]
Infact, this build does not even reflect the speed/inclination on the qz app on treadmill. It has been configured as:
1. Advanced -> Manual > wifi
2. Treadmill -> nordictrack 10 (my treadmill is Nordictrack 1750 but that has never worked), ipaddress: localhost)

Not sure, if I missed something in reconfig.

**Comment by cagnulein** [comment]
What do you mean? You don't read any metrics?

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno ven 21 nov 2025 alle 01:02 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Leave the manual device to disabled

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno ven 21 nov 2025 alle 05:00 cagnulein ***@***.***> ha
scritto:

**Comment by rajivgandhi1** [comment]
No - dont see speed and incline updates in QZ anymore. I did try disabling manual, did not work. Will try that again and let you know.

**Comment by rajivgandhi1** [comment]
I tested it with manual disabled but dont see the speed/incline updates in QZ anymore.

**Comment by cagnulein** [comment]
Ok I will check the log later today

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno ven 21 nov 2025 alle 05:44 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok i'm checking, first the good news, i can see the event of the workout

```
Thu Nov 20 11:54:08 2025 1763668448979 Debug: devices/bluetooth.cpp void bluetooth::debug(const QString &) "Started workout via gRPC WorkoutService"
Thu Nov 20 11:54:17 2025 1763668457978 Debug: devices/bluetooth.cpp void bluetooth::debug(const QString &) "Paused workout via gRPC WorkoutService"
Thu Nov 20 11:54:22 2025 1763668462979 Debug: devices/bluetooth.cpp void bluetooth::debug(const QString &) "Started workout via gRPC WorkoutService"
Thu Nov 20 11:54:34 2025 1763668474978 Debug: devices/bluetooth.cpp void bluetooth::debug(const QString &) "Paused workout via gRPC WorkoutService"
```

so now let's check why you can't see the metrics anymore

**Comment by cagnulein** [comment]
ok i guess i fixed both metrics and workoutstate issue
https://github.com/cagnulein/qdomyos-zwift/actions/runs/19567220708
Let me know!

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno ven 21 nov 2025 alle ore 06:24 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/19570489815

**Comment by rajivgandhi1** [comment]
Tested. Below is the result:
**Metric test:**
1. The metrics speed/incline now work on QZ

**Test from workout player (Start/pause/resume/stop) :**
1. Quick start : works
2. Pause: **Fail** <- When pause is pressed on workout player, it is intercepted by QZ but then it forces an end workout on workout player (but not within QZ)
3. Resume: **Not able to test** - since QZ never allowed to get into a pause state
4. End: **Not able to test** - since QZ never allowed to get into a pause state

**Tests on qz app:**
1. Initial state: **Fail** <- QZ initializes (upon launch) in the started state, see the pause button 
1. Start: works
2. Pause: **Fail** <- When pause is pressed on workout player, it forces an end workout on workout player (but not within QZ)
3. Resume: works
4. Stop: Works <- QZ ends the workout player and ends the workout in QZ.

**Comment by cagnulein** [comment]
So the pause should be a stop in qz?
For the initial state you can change it using the pause on start in the
treadmill options

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
http://paypal.com/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno sab 22 nov 2025 alle 02:53 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by rajivgandhi1** [comment]
pause should be pause in qz

**Comment by cagnulein** [comment]
Hah so you are saying that qz is correctly in pause mode but somehow is triggering something on ifit?

Do you have the debug log of this?

**Comment by rajivgandhi1** [comment]
Not sure we are on the same page - comments below describing the issue. 

Test from workout player (Start/pause/resume/stop) :
1. Quick start : works
2. Pause: Fail <- When pause is pressed on workout player, it is intercepted by QZ but then it forces an end workout on workout player (but not within QZ) 
**In QZ app, the state "pause"  is correct but in workout player, the state is forced to "ended" by qz when the intention was to pause. So no way to "resume" after this**
3. Resume: Not able to test - since QZ never allowed to get into a pause state
4. End: Not able to test - since QZ never allowed to get into a pause state
 

Tests on qz app:
1. Initial state: Fail <- QZ initializes (upon launch) in the started state, see the pause button
2. Start: works
3. Pause: Fail <- When pause is pressed on workout player, it forces an end workout on workout player (but not within QZ) 
**In QZ app, the state "pause"  is correct but in workout player, the state is forced to "ended" by qz when the intention was to pause. So no way to "resume" after this**
4. Resume: works
5. Stop: Works <- QZ ends the workout player and ends the workout in QZ.

**Comment by rajivgandhi1** [comment]
Logs attached

[debug-Fri_Nov_21_23_24_44_2025.log](https://github.com/user-attachments/files/23687407/debug-Fri_Nov_21_23_24_44_2025.log)

**Comment by rajivgandhi1** [comment]
Basically, QZ should have these states & actions in sync with the workout player:
1. Stopped (available workout player actions: "quick start")
2. Running (available workout player actions: "pause" & "end")
3. Paused (available workout player actions: "resume" & "end")

**Comment by cagnulein** [comment]
perfect i added a sw semaphore
https://github.com/cagnulein/qdomyos-zwift/actions/runs/19635368269
let me know if it's better

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno sab 22 nov 2025 alle ore 08:38 rajivgandhi1 <
***@***.***> ha scritto:

**Comment by rajivgandhi1** [comment]
This is still broken (logs attached):
1. First screen (workout player: Quick start, **QZ: "pause" <- should say "start"**)
![Image](https://github.com/user-attachments/assets/d1b2133f-8ce0-4e79-87dc-62e3d45deffe)

2. Hit quick start on workout player (workout player: pause, **QZ: "start" <- should say "pause"**)
![Image](https://github.com/user-attachments/assets/01892187-7b3e-4150-b7c1-7d152b6d4b5b)

3. Hit pause on workout player (workout player: Resume / end, QZ: "pause")
![Image](https://github.com/user-attachments/assets/78930fd4-b05d-45ba-8c42-5babcae3af87)

4. Hit resume on workout player (workout player: pause, **QZ: "start" <- should say "pause"**)
![Image](https://github.com/user-attachments/assets/137ddd74-e1f6-43bf-a55b-5243de11be50)

5. Hit pause on workout player (workout player: Resume / end, QZ: "pause")

6. Hit end on workout player (workout player: Quick start, **QZ: "pause" <- should show the workout complete screen**)
![Image](https://github.com/user-attachments/assets/9aedbd2d-2b3d-4d94-92a0-e066c6b600f9)

[debug-Mon_Nov_24_21_16_32_2025.log](https://github.com/user-attachments/files/23738926/debug-Mon_Nov_24_21_16_32_2025.log)

**Comment by cagnulein** [comment]
Did you try with the pause on start in the treadmill options? It seems simply a desync at the beginning (I'm not reading the startup value from ifit)

**Comment by rajivgandhi1** [comment]
Just tried - no difference. It still starts with the "pause" option instead of "start"

**Comment by cagnulein** [comment]
Ok I will add also a sync at the startup later today

**Comment by rajivgandhi1** [comment]
Pressing end should end the workout and report activity to strava - that did not happen when I tested,

**Comment by cagnulein** [comment]
Do you mean end from the workout player?
Did you sync strava with the new build? You must do this when you are
installing the new version
Does it work if you press stop on qz? Also if the distance is 0 qz doesn't
upload anything

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mar 25 nov 2025 alle 06:50 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by rajivgandhi1** [comment]
Do you mean end from the workout player?
Yes. It seems stop in workout player is not intercepted (as shown in the pictures above)

Did you sync strava with the new build? You must do this when you are installing the new version
I just retested after connecting with strava

Does it work if you press stop on qz? Also if the distance is 0 qz doesn't upload anything
Stopping from QZ works.

**Comment by cagnulein** [comment]
Ok so summarizing :
- adding the sync at startup
- check the stop in the log (did you collect in the log the stop event?)

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mar 25 nov 2025 alle 07:05 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by rajivgandhi1** [comment]
Yes - the log is for the full test

**Comment by cagnulein** [comment]
Perfect I will do later today

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mar 25 nov 2025 alle 07:09 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done both
https://github.com/cagnulein/qdomyos-zwift/actions/runs/19662094637

let me know

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mar 25 nov 2025 alle ore 07:12 cagnulein ***@***.***> ha
scritto:

**Comment by rajivgandhi1** [comment]
The last use case #6 is still broken (logs attached):

1. First screen (workout player: Quick start, QZ: "Start")
2. Hit quick start on workout player (workout player: pause, QZ: "pause")
3. Hit pause on workout player (workout player: Resume / end, QZ: "Start")
4. Hit resume on workout player (workout player: pause, QZ: "pause" )
5. Hit pause on workout player (workout player: Resume / end, QZ: "Start")
6. Hit end on workout player (workout player: Quick start, **QZ: "pause" <- should show the workout complete screen**)

[debug-Tue_Nov_25_17_49_44_2025.log](https://github.com/user-attachments/files/23759942/debug-Tue_Nov_25_17_49_44_2025.log)

**Comment by cagnulein** [comment]
ok also this case should be handled now
https://github.com/cagnulein/qdomyos-zwift/actions/runs/19697767359
thanks

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mer 26 nov 2025 alle ore 03:29 rajivgandhi1 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/19701229189

**Comment by rajivgandhi1** [comment]
#6 is fixed - but more bugs:

1. First screen (workout player: Quick start, QZ: "Start")
2. Hit quick start on workout player (workout player: pause, QZ: "pause")
3. Hit pause on workout player (workout player: Resume / end, QZ: "Start")
4. Hit resume on workout player (workout player: pause, QZ: "pause" )
5. Hit pause on workout player (workout player: Resume / end, QZ: "Start")
6. Hit end on workout player (workout player: Quick start, QZ: "Stop", shows the workout complete screen)
7. Hit quick start on workout player (workout player: pause, **QZ: still shows the prior workout complete screen <- should switch to main screen**)
8. Hit pause in qz (workout player: Resume / end, QZ: "Start")
9. Hit end in qz (workout player: Quick start, QZ: "Stop", shows the workout complete screen)
10. Hit start in qz (workout player: pause, **QZ: "Start" <- should show pause**)
11. Hit start again in qz (workout player: pause, QZ: "pause")
12. Hit pause in qz (**workout player: Quick start <- should say "pause", QZ: shows the workout complete screen**)
13. Hit end on qz (after 11) (workout player: Quick start, QZ: "Stop", shows the workout complete screen)

If I do things aggressively here and there, it goes out of sync. 

The whole state machine & synchronization across qz & workout player is quite fragile. The implementation seems patchy and lacking in a solid distributed FSM design & implementation.  

This is the core of the app - to be able to control & synchronize the treadmill using qz; hence needs a thorough developer testing using a real simulator / treadmill. Else it will remain fragile and cascade into other dependent features. 

[debug-Wed_Nov_26_17_00_27_2025.log](https://github.com/user-attachments/files/23782817/debug-Wed_Nov_26_17_00_27_2025.log)

**Comment by cagnulein** [comment]
I understand your frustration but only you, you are using the app in this
way.
So if you want I can still check what's the issue but I need logs
I don't have an ifit device so it's up to you share and test
Let me know

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno gio 27 nov 2025 alle 02:32 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by rajivgandhi1** [comment]
The logs were attached already:
https://github.com/user-attachments/files/23782817/debug-Wed_Nov_26_17_00_27_2025.log

I dont understand how is this an edge case for the app - the whole purpose of qz is to make non-FTMS treadmills compatible & controllable with apps using FTMS, no?  If QZ cant control the workout consistently and reliably, everything else on top should break as well, no?

**Comment by cagnulein** [comment]
Sorry via email notification the log wasn't there. 

I will check the log

**Comment by cagnulein** [comment]
Anyway I guess it's just an issue on the summary page because from there there is no automatic return to the main screen

**Comment by rajivgandhi1** [comment]
Well, no. There are problems reported further starting step #8

8. Hit pause in qz (workout player: Resume / end, QZ: "Start")
9. Hit end in qz (workout player: Quick start, QZ: "Stop", shows the workout complete screen)
10. Hit start in qz (workout player: pause, **QZ: "Start" <- should show pause**)
11. Hit start again in qz (workout player: pause, QZ: "pause")
12. Hit pause in qz (workout player: **Quick start <- should say "pause", QZ: shows the workout complete screen**)
13. Hit end on qz (after 11) (workout player: Quick start, QZ: "Stop", shows the workout complete screen)

**Comment by cagnulein** [comment]
Ok I guess I will got an explanation for this too

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno gio 27 nov 2025 alle 07:07 rajivgandhi1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
new build
https://github.com/cagnulein/qdomyos-zwift/actions/runs/19730414786

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno gio 27 nov 2025 alle ore 07:08 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/19734426343

**Comment by rajivgandhi1** [comment]
Tested it again - none of the reported issues seem fixed. Also, when it works, its quite fragile and fails to lock step every now and then.

Thanks a lot in trying to get this to work. But I dont think we will be able to resolve this without you having direct access to an actual treadmill so you can experience it yourself. May be we can shelve this for now and hopefully it will be addressed in future. thanks again for your awesome support!

**Comment by cagnulein** [comment]
Ok no problem, feel free to reopen this if you want to test it more
