### ISSUE TITLE
[BUG] Sole F65 goes into warmup mode

### ISSUE THREAD

**Issue by thejefu** [cagnulein/qdomyos-zwift#556]
**Describe the bug**
Using a Sole F65 (treadmill specific setting enabled in options), the treadmill goes into warmup mode anytime the app sends the treadmill data. If I start the app once the treadmill is moving, it will initiate warmup mode as soon as I change speed or incline via the app. If I turn the treadmill on whilst the app is running, the treadmill auto-starts, goes into warmup mode and ends after a few seconds.

I can skip the warm up mode by pressing enter on the treadmill, however the warmup begins again as soon as data is sent.

**To Reproduce**
1. Turn on app with an already moving treadmill.

or

1. Turn the treadmill on with the app running.

**Expected behavior**
I expect the Sol F65 to not go into warmup mode during use.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone8 Plus]
 - OS: iOS 14.4.2

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Wed_Jan_5_19_17_34_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7817330/debug-Wed_Jan_5_19_17_34_2022.log)

**Comment by thejefu** [comment]
Note, the log attached was an instance of turning the treadmill on whilst the app was running.

**Comment by cagnulein** [comment]
i thought @thejefu that you're the same user of #545 :)

**Comment by cagnulein** [comment]
@kasdal do you have the same issue?

**Comment by thejefu** [comment]
I've experienced the same issue on a previous version (and have not evaluated the beta version for this), but no this is a different issue.

**Comment by Kasdal** [comment]
> @Kasdal do you have the same issue?

I don't think so. No.

**Comment by cagnulein** [comment]
@thejefu other than auto incline (that should be already fixed in the 2.9.35), can we close this or we need to investigate more?

**Comment by thejefu** [comment]
It is still an issue unfortunately, I'm not entirely sure how I extended
the warm up time.

**Comment by thejefu** [comment]
@cagnulein however, if you're happy to do away with the F65 setting and get auto incline added for default settings on the F65 (as you mentioned in #545 then I'm happy to close the ticket.

**Comment by cagnulein** [comment]
@thejefu Wait if you have this issue leave it open, we have to understand this, right?

**Comment by Kasdal** [comment]
@thejefu I'm wondering if you are using any of the inbuilt programs on SOLE? 
Because on mine if I power up in manual mode there is no warmup, only on preprogrammed modes.

**Comment by thejefu** [comment]
If I have F65 turned on in the Sole settings and start the treadmill in manual mode, it will enter warmup mode anytime the App does anything. So I can hit enter to end warmup mode and it goes back to manual - but if I change speed on the app or incline via the app, the treadmill beeps and goes into a warmup mode.

I'll make a video for clarity.

**Comment by thejefu** [comment]
https://www.youtube.com/watch?v=i4sDahD7fDI

Video showing the issue.

**Comment by Kasdal** [comment]
Roberto will have a better idea probably, but from the video, my best guess is that you are losing BT connection because your information from the treadmill does not correspond to the data on QZ.

**Comment by thejefu** [comment]
I noticed that - that has never happened before. But you will note later in
the video when it does correspond it still happens and has historically
still been the case.

**Comment by cagnulein** [comment]
@thejefu is it possible that it's a treadmill configuration? did you try to do a factory reset on it? if @Kasdal doesn't see it, it's my only explanation

Can you guys compare the firmware version of your treadmil? Maybe that's another possible cause of this

**Comment by thejefu** [comment]
Software is version 1.1

**Comment by Kasdal** [comment]
Same here 1.1

**Comment by thejefu** [comment]
@cagnulein received beta 2.9 (15)

Tested with F65 enabled. Warmup mode is obviously still a problem. I can get 3 minutes in warmup mode by pressing enter to skip it, pushing my timer upto 3 minutes and then I leave it to enter warmup mode and it counts out the 3 minutes.

If I leave the treadmill in warmup mode for those 3 minutes, auto inclination works perfectly, but my speed keeps increasing by 0.1 every couple of seconds.

**Comment by thejefu** [comment]
@Kasdal I can't think of any other variables that differ. I do have a Stryd connecting via bluetooth but it is stationary.

**Comment by Kasdal** [comment]
Did you try installing QZ on another device? Could be a BT issue but that would show in your logs I guess.
I know there are differences in models for US and EU markets and the US will not work natively with Zwift for some models but it should not affect you in bridged mode over QZ.

**Comment by thejefu** [comment]
Tried my iPad for QZ, same problem.

**Comment by thejefu** [comment]
I'll see if I can get QZ going on my Windows Laptop if that's possible.

**Comment by Kasdal** [comment]
I believe it only works on Unix systems. Linux and Mac. You could try a VM and install a Linux or use WSL on windows 10.

**Comment by cagnulein** [comment]
@thejefu did you try a factory reset on the treadmill?

**Comment by cagnulein** [comment]
@Kasdal i don't think it's a OS issue the warmup one unfortunately

**Comment by thejefu** [comment]
Closest thing I could find was holding Start/Speed Up where you changed the units and it runs a recalibration. Made no difference.

**Comment by cagnulein** [comment]
could you guys try to generate a simple workout (without zwift) just to compare the behaviour of the treadmill? @thejefu  @Kasdal 
For example, just connect to QZ and start the treadmill. If i understood well, on the @thejefu one, it will start a warmup, instead, on the @Kasdal doesn't.
If so i can understand this issue better
Thanks

**Comment by thejefu** [comment]
I'll do this later today. I did notice something strange last night - I've
only recently got back into running and have been sticking below hour+
runs. When my treadmill hit a 60:00 minutes of elapsed time on my run last
night it started doing exactly the same thing it does with QZ, continuously
trying to enter warmup mode.

**Comment by Kasdal** [comment]
> could you guys try to generate a simple workout (without zwift) just to compare the behaviour of the treadmill? @thejefu @Kasdal For example, just connect to QZ and start the treadmill. If i understood well, on the @thejefu one, it will start a warmup, instead, on the @Kasdal doesn't. If so i can understand this issue better Thanks

I have no issues with a warmup so far. But I do still need to kick it up at a higher speed, to begin with.

**Comment by thejefu** [comment]
[debug-Mon_Jan_10_22_30_42_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7842279/debug-Mon_Jan_10_22_30_42_2022.log)

Short and sweet. Turned on treadmill, turned on QZ, started a manual run, goes into and ends warmup mode immediately.

**Comment by cagnulein** [comment]
ok thanks @thejefu . @Kasdal can you do the same to compare them?

**Comment by Kasdal** [comment]
I did the same. Left it running for about 10 min. No issues. 
@thejefu Could it maybe be your countdown timer set to low?

**Comment by thejefu** [comment]
I'm starting from manual, counts up from 0. Think it displays 30:00 in the timer when I hit start.

@Kasdal is your Sole F65 checked?

**Comment by thejefu** [comment]
I tried doing a manual workout and setting the time to 99:99.

It started warmup mode shortly after starting, then just kept ramping up the incline and speed incrementely.

**Comment by Kasdal** [comment]
> I'm starting from manual, counts up from 0. Think it displays 30:00 in the timer when I hit start.
> 
> @Kasdal is your Sole F65 checked?

What do you mean by checked?

**Comment by Kasdal** [comment]
> I tried doing a manual workout and setting the time to 99:99.
> 
> It started warmup mode shortly after starting, then just kept ramping up the incline and speed incrementely.

Yeah same thing is happening to me if i try to adjust over the app i touch it once and it will go to the max setting. I just use the physical buttons on the Sole.

**Comment by thejefu** [comment]
> > I'm starting from manual, counts up from 0. Think it displays 30:00 in the timer when I hit start.
> > @Kasdal is your Sole F65 checked?
> 
> What do you mean by checked?

Is it turned on or off?

**Comment by thejefu** [comment]
In the treadmill settings.

**Comment by Kasdal** [comment]
> > > I'm starting from manual, counts up from 0. Think it displays 30:00 in the timer when I hit start.
> > > @Kasdal is your Sole F65 checked?
> > 
> > 
> > What do you mean by checked?
> 
> Is it turned on or off In the treadmill settings?

Ahh yeah, it's toggled off. It does not work for me with that option activated.

**Comment by thejefu** [comment]
Out of curiosity, what happens if you:

1) Set F65 setting to on, turn off QZ
2) Turn treadmill on
3) Turn on QZ
4) Hit start on the treadmill in manual mode

**Comment by Kasdal** [comment]
I get locked out of control

**Comment by cagnulein** [comment]
@Kasdal @thejefu any update on this?

**Comment by thejefu** [comment]
Still where I was at Roberto. Treadmills been out of action 2 weeks since I
had the motor replaced to address an issue I had with the incline. Have you
made any changes in updates since we last spoke?

**Comment by cagnulein** [comment]
yes i worked a lot with another user for the #597 so maybe it could be useful for you too, idk
Anyway let's wait the new motor and we will see
Have a nice weekend!

**Comment by cagnulein** [comment]
any news about the motor @thejefu  ?
